DROP TRIGGER IF EXISTS trg_jobs_search_vector_update ON jobs;
DROP FUNCTION IF EXISTS update_job_search_vector();
DROP PROCEDURE IF EXISTS expire_stale_jobs(UUID);
DROP TABLE IF EXISTS jobs CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
DROP TYPE IF EXISTS job_status CASCADE;

-- Enable required extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Define custom ENUM for job lifecycle management
CREATE TYPE job_status AS ENUM ('ACTIVE', 'STALE', 'EXPIRED', 'ARCHIVED');

-- 1. Companies Table
CREATE TABLE companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    ats_type VARCHAR(50) NOT NULL,            
    board_token VARCHAR(255) NOT NULL UNIQUE,        
    website_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Jobs Table
CREATE TABLE jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    company_name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    
    -- Role & Compensation
    experience_level VARCHAR(50),              
    employment_type VARCHAR(50),               
    salary_min INTEGER,                        
    salary_max INTEGER,                        
    salary_currency VARCHAR(10) DEFAULT 'USD', 
    
    location VARCHAR(255),
    department VARCHAR(255),
    description_text TEXT,
    apply_url TEXT NOT NULL,
    ats_job_id VARCHAR(100),                  
    
    -- Lifecycle State
    status job_status DEFAULT 'ACTIVE',
    
    -- Timestamps
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    
    -- PostgreSQL Full-Text Search Vector
    search_vector tsvector
);

-- 3. Indexes for Sub-Millisecond Search Performance
CREATE INDEX idx_jobs_search_vector ON jobs USING GIN (search_vector);
CREATE INDEX idx_jobs_active_created ON jobs(status, created_at DESC);
CREATE INDEX idx_jobs_company_id ON jobs(company_id);
CREATE INDEX idx_jobs_sweep_optimizer ON jobs(company_id, last_seen_at) WHERE status = 'ACTIVE';

-- 4. Automated Search Vector Trigger
CREATE OR REPLACE FUNCTION update_job_search_vector() RETURNS trigger AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.experience_level, '')), 'A') || 
        setweight(to_tsvector('english', coalesce(NEW.department, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.location, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.description_text, '')), 'C');
    RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_jobs_search_vector_update
BEFORE INSERT OR UPDATE ON jobs
FOR EACH ROW EXECUTE FUNCTION update_job_search_vector();

-- 5. The Sweeper Procedure
CREATE OR REPLACE PROCEDURE expire_stale_jobs(target_company_id UUID)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE jobs 
    SET status = 'EXPIRED'
    WHERE company_id = target_company_id 
      AND status = 'ACTIVE' 
      AND last_seen_at < (CURRENT_TIMESTAMP - INTERVAL '24 hours');
END;
$$;

SELECT current_database();

-- =========================================================================
-- 1. INSERT: Talentera Portals
-- =========================================================================
INSERT INTO companies (name, ats_type, board_token, website_url) VALUES 
('Abdullah Abdulghani & Bros (AAB)', 'TALENTERA', 'aab', 'https://aab.talentera.com'),
('Telecommunications Regulatory Authority', 'TALENTERA', 'tra', 'https://tra.talentera.com'),
('Royal Jordanian', 'TALENTERA', 'royaljordanian', 'https://royaljordanian.talentera.com'),
('Mobica', 'TALENTERA', 'mobica', 'https://mobica.talentera.com'),
('Masar', 'TALENTERA', 'masar', 'https://masar.talentera.com'),
('Tamimi Markets', 'TALENTERA', 'tamimi', 'https://tamimi.talentera.com'),
('Mobily', 'TALENTERA', 'mobily', 'https://mobily.talentera.com'),
('Orange Bed & Bath', 'TALENTERA', 'orangebedbath', 'https://orangebedbath.talentera.com'),
('Magrabi', 'TALENTERA', 'magrabi', 'https://magrabi.talentera.com'),
('Rawabi Holding', 'TALENTERA', 'rawabi', 'https://rawabi.talentera.com'),
('Itqan', 'TALENTERA', 'itqan', 'https://itqan.talentera.com'),
('Council of Health Insurance (CHI)', 'TALENTERA', 'chi', 'https://chi.talentera.com'),
('Radwa Food Products', 'TALENTERA', 'radwa', 'https://radwa.talentera.com'),
('Talentera Careers', 'TALENTERA', 'careers', 'https://careers.talentera.com'),
('Integral', 'TALENTERA', 'integral', 'https://integral.talentera.com'),
('National Center for Environmental Compliance (NCEC)', 'TALENTERA', 'ncec', 'https://ncec.talentera.com'),
('Panda Retail Company', 'TALENTERA', 'panda', 'https://panda.talentera.com'),
('BEAM', 'TALENTERA', 'beam', 'https://beam.talentera.com'),
('Care National Hospital', 'TALENTERA', 'care', 'https://care.talentera.com'),
('Badruddin', 'TALENTERA', 'badruddin', 'https://badruddin.talentera.com'),
('Saudi Investment Bank (SAIB)', 'TALENTERA', 'saib', 'https://saib.talentera.com'),
('General Organization for Social Insurance (GOSI)', 'TALENTERA', 'gosi', 'https://gosi.talentera.com'),
('Al-Dawaa Pharmacies', 'TALENTERA', 'al-dawaa', 'https://al-dawaa.talentera.com'),
('Save the Children', 'TALENTERA', 'savethechildren', 'https://savethechildren.talentera.com'),
('Taiba Investments', 'TALENTERA', 'taiba', 'https://taiba.talentera.com'),
('Concrete', 'TALENTERA', 'concrete', 'https://concrete.talentera.com'),
('Maliks', 'TALENTERA', 'maliks', 'https://maliks.talentera.com'),
('Ejada', 'TALENTERA', 'ejada', 'https://ejada.talentera.com'),
('Talentera Demo', 'TALENTERA', 'demo', 'https://demo.talentera.com'),
('Saudi Bar Association (SBA)', 'TALENTERA', 'sba', 'https://sba.talentera.com'),
('Choithrams', 'TALENTERA', 'choithrams', 'https://choithrams.talentera.com'),
('Alfardan Group', 'TALENTERA', 'alfardan', 'https://alfardan.talentera.com'),
('Gulf International Bank (GIB)', 'TALENTERA', 'gib', 'https://gib.talentera.com'),
('MSD', 'TALENTERA', 'msd', 'https://msd.talentera.com'),
('SAL Saudi Logistics Services', 'TALENTERA', 'sal', 'https://sal.talentera.com'),
('Saudi Petroleum Services Polytechnic (SPSP)', 'TALENTERA', 'spsp', 'https://spsp.talentera.com'),
('Batelco', 'TALENTERA', 'batelco', 'https://batelco.talentera.com'),
('National Water Company (NWC)', 'TALENTERA', 'nwc', 'https://nwc.talentera.com'),
('Capital Market Authority (CMA)', 'TALENTERA', 'cma', 'https://cma.talentera.com'),
('MODON', 'TALENTERA', 'modon', 'https://modon.talentera.com'),
('Al Rashed', 'TALENTERA', 'alrashed', 'https://alrashed.talentera.com')
ON CONFLICT (board_token) DO UPDATE 
SET name = EXCLUDED.name, ats_type = EXCLUDED.ats_type;


-- =========================================================================
-- 2. INSERT: Greenhouse Portals
-- =========================================================================
INSERT INTO companies (name, ats_type, board_token, website_url) VALUES 
('Gps', 'GREENHOUSE', 'gps', 'https://boards.greenhouse.io/gps'),
('London', 'GREENHOUSE', 'london', 'https://boards.greenhouse.io/london'),
('Orca', 'GREENHOUSE', 'orca', 'https://boards.greenhouse.io/orca'),
('Spotlight', 'GREENHOUSE', 'spotlight', 'https://boards.greenhouse.io/spotlight'),
('Kayak', 'GREENHOUSE', 'kayak', 'https://boards.greenhouse.io/kayak'),
('National', 'GREENHOUSE', 'national', 'https://boards.greenhouse.io/national'),
('Alx', 'GREENHOUSE', 'alx', 'https://boards.greenhouse.io/alx'),
('Gemini', 'GREENHOUSE', 'gemini', 'https://boards.greenhouse.io/gemini'),
('Concentric', 'GREENHOUSE', 'concentric', 'https://boards.greenhouse.io/concentric'),
('Magnolia', 'GREENHOUSE', 'magnolia', 'https://boards.greenhouse.io/magnolia'),
('Stage', 'GREENHOUSE', 'stage', 'https://boards.greenhouse.io/stage'),
('Galileo', 'GREENHOUSE', 'galileo', 'https://boards.greenhouse.io/galileo'),
('Raven', 'GREENHOUSE', 'raven', 'https://boards.greenhouse.io/raven'),
('Super', 'GREENHOUSE', 'super', 'https://boards.greenhouse.io/super'),
('Digit', 'GREENHOUSE', 'digit', 'https://boards.greenhouse.io/digit'),
('Apollo', 'GREENHOUSE', 'apollo', 'https://boards.greenhouse.io/apollo'),
('Tulip', 'GREENHOUSE', 'tulip', 'https://boards.greenhouse.io/tulip'),
('Pvi', 'GREENHOUSE', 'pvi', 'https://boards.greenhouse.io/pvi'),
('Denver', 'GREENHOUSE', 'denver', 'https://boards.greenhouse.io/denver'),
('Chicago', 'GREENHOUSE', 'chicago', 'https://boards.greenhouse.io/chicago'),
('Tide', 'GREENHOUSE', 'tide', 'https://boards.greenhouse.io/tide'),
('Flourish', 'GREENHOUSE', 'flourish', 'https://boards.greenhouse.io/flourish'),
('Bob', 'GREENHOUSE', 'bob', 'https://boards.greenhouse.io/bob'),
('Brothers', 'GREENHOUSE', 'brothers', 'https://boards.greenhouse.io/brothers'),
('Taa', 'GREENHOUSE', 'taa', 'https://boards.greenhouse.io/taa'),
('Regent', 'GREENHOUSE', 'regent', 'https://boards.greenhouse.io/regent'),
('Nex', 'GREENHOUSE', 'nex', 'https://boards.greenhouse.io/nex'),
('Abc', 'GREENHOUSE', 'abc', 'https://boards.greenhouse.io/abc'),
('Flamingo', 'GREENHOUSE', 'flamingo', 'https://boards.greenhouse.io/flamingo'),
('Glow', 'GREENHOUSE', 'glow', 'https://boards.greenhouse.io/glow'),
('Reflex', 'GREENHOUSE', 'reflex', 'https://boards.greenhouse.io/reflex'),
('Korea', 'GREENHOUSE', 'korea', 'https://boards.greenhouse.io/korea'),
('Its', 'GREENHOUSE', 'its', 'https://boards.greenhouse.io/its'),
('Coast', 'GREENHOUSE', 'coast', 'https://boards.greenhouse.io/coast'),
('Indigo', 'GREENHOUSE', 'indigo', 'https://boards.greenhouse.io/indigo'),
('Metropolis', 'GREENHOUSE', 'metropolis', 'https://boards.greenhouse.io/metropolis'),
('Oldcity', 'GREENHOUSE', 'oldcity', 'https://boards.greenhouse.io/oldcity'),
('Paradigm', 'GREENHOUSE', 'paradigm', 'https://boards.greenhouse.io/paradigm'),
('Alabaster', 'GREENHOUSE', 'alabaster', 'https://boards.greenhouse.io/alabaster'),
('Octave', 'GREENHOUSE', 'octave', 'https://boards.greenhouse.io/octave'),
('Reliant', 'GREENHOUSE', 'reliant', 'https://boards.greenhouse.io/reliant'),
('Headquarter', 'GREENHOUSE', 'headquarter', 'https://boards.greenhouse.io/headquarter'),
('Lightworks', 'GREENHOUSE', 'lightworks', 'https://boards.greenhouse.io/lightworks'),
('Bloom', 'GREENHOUSE', 'bloom', 'https://boards.greenhouse.io/bloom'),
('Rak', 'GREENHOUSE', 'rak', 'https://boards.greenhouse.io/rak'),
('Shield', 'GREENHOUSE', 'shield', 'https://boards.greenhouse.io/shield'),
('Upkeep', 'GREENHOUSE', 'upkeep', 'https://boards.greenhouse.io/upkeep'),
('Truemedia', 'GREENHOUSE', 'truemedia', 'https://boards.greenhouse.io/truemedia'),
('Soci', 'GREENHOUSE', 'soci', 'https://boards.greenhouse.io/soci'),
('Dna', 'GREENHOUSE', 'dna', 'https://boards.greenhouse.io/dna'),
('Administrative', 'GREENHOUSE', 'administrative', 'https://boards.greenhouse.io/administrative'),
('Athletics', 'GREENHOUSE', 'athletics', 'https://boards.greenhouse.io/athletics'),
('Sei', 'GREENHOUSE', 'sei', 'https://boards.greenhouse.io/sei'),
('Metro', 'GREENHOUSE', 'metro', 'https://boards.greenhouse.io/metro'),
('Athena', 'GREENHOUSE', 'athena', 'https://boards.greenhouse.io/athena'),
('Support', 'GREENHOUSE', 'support', 'https://boards.greenhouse.io/support'),
('Hunterdouglas', 'GREENHOUSE', 'hunterdouglas', 'https://boards.greenhouse.io/hunterdouglas'),
('Zoro', 'GREENHOUSE', 'zoro', 'https://boards.greenhouse.io/zoro'),
('Carbon', 'GREENHOUSE', 'carbon', 'https://boards.greenhouse.io/carbon'),
('Greenline', 'GREENHOUSE', 'greenline', 'https://boards.greenhouse.io/greenline'),
('Pioneer', 'GREENHOUSE', 'pioneer', 'https://boards.greenhouse.io/pioneer'),
('Yes', 'GREENHOUSE', 'yes', 'https://boards.greenhouse.io/yes'),
('Avani', 'GREENHOUSE', 'avani', 'https://boards.greenhouse.io/avani'),
('Help', 'GREENHOUSE', 'help', 'https://boards.greenhouse.io/help'),
('Eclipse', 'GREENHOUSE', 'eclipse', 'https://boards.greenhouse.io/eclipse'),
('Jaguar', 'GREENHOUSE', 'jaguar', 'https://boards.greenhouse.io/jaguar'),
('Dino', 'GREENHOUSE', 'dino', 'https://boards.greenhouse.io/dino'),
('Koko', 'GREENHOUSE', 'koko', 'https://boards.greenhouse.io/koko'),
('Rmr', 'GREENHOUSE', 'rmr', 'https://boards.greenhouse.io/rmr'),
('New', 'GREENHOUSE', 'new', 'https://boards.greenhouse.io/new'),
('Sao', 'GREENHOUSE', 'sao', 'https://boards.greenhouse.io/sao'),
('Tomorrow', 'GREENHOUSE', 'tomorrow', 'https://boards.greenhouse.io/tomorrow'),
('Stone', 'GREENHOUSE', 'stone', 'https://boards.greenhouse.io/stone'),
('Seed', 'GREENHOUSE', 'seed', 'https://boards.greenhouse.io/seed'),
('Iris', 'GREENHOUSE', 'iris', 'https://boards.greenhouse.io/iris'),
('Comet', 'GREENHOUSE', 'comet', 'https://boards.greenhouse.io/comet'),
('Investment', 'GREENHOUSE', 'investment', 'https://boards.greenhouse.io/investment'),
('Ghost', 'GREENHOUSE', 'ghost', 'https://boards.greenhouse.io/ghost'),
('Casa', 'GREENHOUSE', 'casa', 'https://boards.greenhouse.io/casa'),
('Nursing', 'GREENHOUSE', 'nursing', 'https://boards.greenhouse.io/nursing'),
('Shaker', 'GREENHOUSE', 'shaker', 'https://boards.greenhouse.io/shaker'),
('Encore', 'GREENHOUSE', 'encore', 'https://boards.greenhouse.io/encore'),
('Range', 'GREENHOUSE', 'range', 'https://boards.greenhouse.io/range'),
('Ref', 'GREENHOUSE', 'ref', 'https://boards.greenhouse.io/ref'),
('Moneymart', 'GREENHOUSE', 'moneymart', 'https://boards.greenhouse.io/moneymart'),
('Excel', 'GREENHOUSE', 'excel', 'https://boards.greenhouse.io/excel'),
('Optimal', 'GREENHOUSE', 'optimal', 'https://boards.greenhouse.io/optimal'),
('Gateway', 'GREENHOUSE', 'gateway', 'https://boards.greenhouse.io/gateway'),
('Reach', 'GREENHOUSE', 'reach', 'https://boards.greenhouse.io/reach'),
('Slice', 'GREENHOUSE', 'slice', 'https://boards.greenhouse.io/slice'),
('Forward', 'GREENHOUSE', 'forward', 'https://boards.greenhouse.io/forward'),
('Fox', 'GREENHOUSE', 'fox', 'https://boards.greenhouse.io/fox'),
('Isa', 'GREENHOUSE', 'isa', 'https://boards.greenhouse.io/isa'),
('Murad', 'GREENHOUSE', 'murad', 'https://boards.greenhouse.io/murad'),
('Sunrise', 'GREENHOUSE', 'sunrise', 'https://boards.greenhouse.io/sunrise'),
('Sada', 'GREENHOUSE', 'sada', 'https://boards.greenhouse.io/sada'),
('Pine', 'GREENHOUSE', 'pine', 'https://boards.greenhouse.io/pine'),
('Charles', 'GREENHOUSE', 'charles', 'https://boards.greenhouse.io/charles'),
('Proton', 'GREENHOUSE', 'proton', 'https://boards.greenhouse.io/proton'),
('Clever', 'GREENHOUSE', 'clever', 'https://boards.greenhouse.io/clever'),
('Sts', 'GREENHOUSE', 'sts', 'https://boards.greenhouse.io/sts'),
('Private', 'GREENHOUSE', 'private', 'https://boards.greenhouse.io/private'),
('Netherlands', 'GREENHOUSE', 'netherlands', 'https://boards.greenhouse.io/netherlands'),
('Hala', 'GREENHOUSE', 'hala', 'https://boards.greenhouse.io/hala'),
('Amca', 'GREENHOUSE', 'amca', 'https://boards.greenhouse.io/amca'),
('Truckstop', 'GREENHOUSE', 'truckstop', 'https://boards.greenhouse.io/truckstop'),
('Moon', 'GREENHOUSE', 'moon', 'https://boards.greenhouse.io/moon'),
('Boulevard', 'GREENHOUSE', 'boulevard', 'https://boards.greenhouse.io/boulevard'),
('Parkland', 'GREENHOUSE', 'parkland', 'https://boards.greenhouse.io/parkland'),
('Axiom', 'GREENHOUSE', 'axiom', 'https://boards.greenhouse.io/axiom'),
('Newhope', 'GREENHOUSE', 'newhope', 'https://boards.greenhouse.io/newhope'),
('Sonic', 'GREENHOUSE', 'sonic', 'https://boards.greenhouse.io/sonic'),
('Techno', 'GREENHOUSE', 'techno', 'https://boards.greenhouse.io/techno'),
('Genuine', 'GREENHOUSE', 'genuine', 'https://boards.greenhouse.io/genuine'),
('Careem', 'GREENHOUSE', 'careem', 'https://boards.greenhouse.io/careem'),
('Tribal', 'GREENHOUSE', 'tribal', 'https://boards.greenhouse.io/tribal'),
('Drc', 'GREENHOUSE', 'drc', 'https://boards.greenhouse.io/drc'),
('Homeland', 'GREENHOUSE', 'homeland', 'https://boards.greenhouse.io/homeland'),
('Vibes', 'GREENHOUSE', 'vibes', 'https://boards.greenhouse.io/vibes'),
('Mesh', 'GREENHOUSE', 'mesh', 'https://boards.greenhouse.io/mesh'),
('Chata', 'GREENHOUSE', 'chata', 'https://boards.greenhouse.io/chata'),
('Cabin', 'GREENHOUSE', 'cabin', 'https://boards.greenhouse.io/cabin'),
('Kansas', 'GREENHOUSE', 'kansas', 'https://boards.greenhouse.io/kansas'),
('Polaris', 'GREENHOUSE', 'polaris', 'https://boards.greenhouse.io/polaris'),
('Peak', 'GREENHOUSE', 'peak', 'https://boards.greenhouse.io/peak'),
('Magic', 'GREENHOUSE', 'magic', 'https://boards.greenhouse.io/magic'),
('Oscar', 'GREENHOUSE', 'oscar', 'https://boards.greenhouse.io/oscar'),
('Mobi', 'GREENHOUSE', 'mobi', 'https://boards.greenhouse.io/mobi'),
('Broadway', 'GREENHOUSE', 'broadway', 'https://boards.greenhouse.io/broadway'),
('Efs', 'GREENHOUSE', 'efs', 'https://boards.greenhouse.io/efs'),
('Sterling', 'GREENHOUSE', 'sterling', 'https://boards.greenhouse.io/sterling'),
('Integrated', 'GREENHOUSE', 'integrated', 'https://boards.greenhouse.io/integrated'),
('Isam', 'GREENHOUSE', 'isam', 'https://boards.greenhouse.io/isam'),
('Link', 'GREENHOUSE', 'link', 'https://boards.greenhouse.io/link'),
('Evergreen', 'GREENHOUSE', 'evergreen', 'https://boards.greenhouse.io/evergreen'),
('Ideo', 'GREENHOUSE', 'ideo', 'https://boards.greenhouse.io/ideo'),
('Candles', 'GREENHOUSE', 'candles', 'https://boards.greenhouse.io/candles'),
('Flex', 'GREENHOUSE', 'flex', 'https://boards.greenhouse.io/flex'),
('Gusto', 'GREENHOUSE', 'gusto', 'https://boards.greenhouse.io/gusto'),
('Maxwell', 'GREENHOUSE', 'maxwell', 'https://boards.greenhouse.io/maxwell'),
('Make', 'GREENHOUSE', 'make', 'https://boards.greenhouse.io/make'),
('Industrial', 'GREENHOUSE', 'industrial', 'https://boards.greenhouse.io/industrial'),
('Mit', 'GREENHOUSE', 'mit', 'https://boards.greenhouse.io/mit'),
('Wundermanthompson', 'GREENHOUSE', 'wundermanthompson', 'https://boards.greenhouse.io/wundermanthompson'),
('Talent', 'GREENHOUSE', 'talent', 'https://boards.greenhouse.io/talent'),
('Independent', 'GREENHOUSE', 'independent', 'https://boards.greenhouse.io/independent'),
('Makina', 'GREENHOUSE', 'makina', 'https://boards.greenhouse.io/makina'),
('David', 'GREENHOUSE', 'david', 'https://boards.greenhouse.io/david'),
('Tcs', 'GREENHOUSE', 'tcs', 'https://boards.greenhouse.io/tcs'),
('Firstday', 'GREENHOUSE', 'firstday', 'https://boards.greenhouse.io/firstday'),
('Calm', 'GREENHOUSE', 'calm', 'https://boards.greenhouse.io/calm'),
('Sas', 'GREENHOUSE', 'sas', 'https://boards.greenhouse.io/sas'),
('Victory', 'GREENHOUSE', 'victory', 'https://boards.greenhouse.io/victory'),
('Emi', 'GREENHOUSE', 'emi', 'https://boards.greenhouse.io/emi'),
('Nexus', 'GREENHOUSE', 'nexus', 'https://boards.greenhouse.io/nexus'),
('Regie', 'GREENHOUSE', 'regie', 'https://boards.greenhouse.io/regie'),
('Solutions', 'GREENHOUSE', 'solutions', 'https://boards.greenhouse.io/solutions'),
('B12', 'GREENHOUSE', 'b12', 'https://boards.greenhouse.io/b12'),
('Dallas', 'GREENHOUSE', 'dallas', 'https://boards.greenhouse.io/dallas'),
('Sabino', 'GREENHOUSE', 'sabino', 'https://boards.greenhouse.io/sabino'),
('Kit', 'GREENHOUSE', 'kit', 'https://boards.greenhouse.io/kit'),
('Japan', 'GREENHOUSE', 'japan', 'https://boards.greenhouse.io/japan'),
('Antigua', 'GREENHOUSE', 'antigua', 'https://boards.greenhouse.io/antigua'),
('Imc', 'GREENHOUSE', 'imc', 'https://boards.greenhouse.io/imc'),
('Testing', 'GREENHOUSE', 'testing', 'https://boards.greenhouse.io/testing'),
('Elitetechnology', 'GREENHOUSE', 'elitetechnology', 'https://boards.greenhouse.io/elitetechnology'),
('General', 'GREENHOUSE', 'general', 'https://boards.greenhouse.io/general'),
('Gravity', 'GREENHOUSE', 'gravity', 'https://boards.greenhouse.io/gravity'),
('Tss', 'GREENHOUSE', 'tss', 'https://boards.greenhouse.io/tss'),
('Sunset', 'GREENHOUSE', 'sunset', 'https://boards.greenhouse.io/sunset'),
('Jay', 'GREENHOUSE', 'jay', 'https://boards.greenhouse.io/jay'),
('Scanner', 'GREENHOUSE', 'scanner', 'https://boards.greenhouse.io/scanner'),
('Workshop', 'GREENHOUSE', 'workshop', 'https://boards.greenhouse.io/workshop'),
('Explore', 'GREENHOUSE', 'explore', 'https://boards.greenhouse.io/explore'),
('Flix', 'GREENHOUSE', 'flix', 'https://boards.greenhouse.io/flix'),
('Space', 'GREENHOUSE', 'space', 'https://boards.greenhouse.io/space'),
('Universal', 'GREENHOUSE', 'universal', 'https://boards.greenhouse.io/universal'),
('Journey', 'GREENHOUSE', 'journey', 'https://boards.greenhouse.io/journey'),
('Tec', 'GREENHOUSE', 'tec', 'https://boards.greenhouse.io/tec'),
('Galaxy', 'GREENHOUSE', 'galaxy', 'https://boards.greenhouse.io/galaxy'),
('Branch', 'GREENHOUSE', 'branch', 'https://boards.greenhouse.io/branch'),
('Echo', 'GREENHOUSE', 'echo', 'https://boards.greenhouse.io/echo'),
('Location', 'GREENHOUSE', 'location', 'https://boards.greenhouse.io/location'),
('Shadow', 'GREENHOUSE', 'shadow', 'https://boards.greenhouse.io/shadow'),
('Edison', 'GREENHOUSE', 'edison', 'https://boards.greenhouse.io/edison'),
('Tiptop', 'GREENHOUSE', 'tiptop', 'https://boards.greenhouse.io/tiptop'),
('Philippines', 'GREENHOUSE', 'philippines', 'https://boards.greenhouse.io/philippines'),
('Name', 'GREENHOUSE', 'name', 'https://boards.greenhouse.io/name'),
('Mas', 'GREENHOUSE', 'mas', 'https://boards.greenhouse.io/mas'),
('Res', 'GREENHOUSE', 'res', 'https://boards.greenhouse.io/res'),
('Tpm', 'GREENHOUSE', 'tpm', 'https://boards.greenhouse.io/tpm'),
('Lighthouse', 'GREENHOUSE', 'lighthouse', 'https://boards.greenhouse.io/lighthouse'),
('Champion', 'GREENHOUSE', 'champion', 'https://boards.greenhouse.io/champion'),
('Ensemble', 'GREENHOUSE', 'ensemble', 'https://boards.greenhouse.io/ensemble'),
('Bold', 'GREENHOUSE', 'bold', 'https://boards.greenhouse.io/bold'),
('Bridgeway', 'GREENHOUSE', 'bridgeway', 'https://boards.greenhouse.io/bridgeway'),
('Clear', 'GREENHOUSE', 'clear', 'https://boards.greenhouse.io/clear'),
('Any', 'GREENHOUSE', 'any', 'https://boards.greenhouse.io/any'),
('Newton', 'GREENHOUSE', 'newton', 'https://boards.greenhouse.io/newton'),
('Cts', 'GREENHOUSE', 'cts', 'https://boards.greenhouse.io/cts'),
('Joya', 'GREENHOUSE', 'joya', 'https://boards.greenhouse.io/joya'),
('Finance', 'GREENHOUSE', 'finance', 'https://boards.greenhouse.io/finance'),
('Axon', 'GREENHOUSE', 'axon', 'https://boards.greenhouse.io/axon'),
('Aziz', 'GREENHOUSE', 'aziz', 'https://boards.greenhouse.io/aziz'),
('Symphony', 'GREENHOUSE', 'symphony', 'https://boards.greenhouse.io/symphony'),
('Aura', 'GREENHOUSE', 'aura', 'https://boards.greenhouse.io/aura'),
('Coop', 'GREENHOUSE', 'coop', 'https://boards.greenhouse.io/coop'),
('Gmp', 'GREENHOUSE', 'gmp', 'https://boards.greenhouse.io/gmp'),
('Future', 'GREENHOUSE', 'future', 'https://boards.greenhouse.io/future'),
('Locals', 'GREENHOUSE', 'locals', 'https://boards.greenhouse.io/locals'),
('Orchestra', 'GREENHOUSE', 'orchestra', 'https://boards.greenhouse.io/orchestra'),
('Cycles', 'GREENHOUSE', 'cycles', 'https://boards.greenhouse.io/cycles'),
('Contracts', 'GREENHOUSE', 'contracts', 'https://boards.greenhouse.io/contracts'),
('Bees', 'GREENHOUSE', 'bees', 'https://boards.greenhouse.io/bees'),
('Shepherd', 'GREENHOUSE', 'shepherd', 'https://boards.greenhouse.io/shepherd'),
('Daylight', 'GREENHOUSE', 'daylight', 'https://boards.greenhouse.io/daylight'),
('Hologram', 'GREENHOUSE', 'hologram', 'https://boards.greenhouse.io/hologram'),
('Pharmacy', 'GREENHOUSE', 'pharmacy', 'https://boards.greenhouse.io/pharmacy'),
('Ultimate', 'GREENHOUSE', 'ultimate', 'https://boards.greenhouse.io/ultimate'),
('Vaya', 'GREENHOUSE', 'vaya', 'https://boards.greenhouse.io/vaya'),
('Engine', 'GREENHOUSE', 'engine', 'https://boards.greenhouse.io/engine'),
('Intercom', 'GREENHOUSE', 'intercom', 'https://boards.greenhouse.io/intercom'),
('Events', 'GREENHOUSE', 'events', 'https://boards.greenhouse.io/events'),
('Find', 'GREENHOUSE', 'find', 'https://boards.greenhouse.io/find'),
('Test', 'GREENHOUSE', 'test', 'https://boards.greenhouse.io/test'),
('Keen', 'GREENHOUSE', 'keen', 'https://boards.greenhouse.io/keen'),
('Public', 'GREENHOUSE', 'public', 'https://boards.greenhouse.io/public'),
('Highland', 'GREENHOUSE', 'highland', 'https://boards.greenhouse.io/highland'),
('Sra', 'GREENHOUSE', 'sra', 'https://boards.greenhouse.io/sra'),
('Forte', 'GREENHOUSE', 'forte', 'https://boards.greenhouse.io/forte'),
('Disney', 'GREENHOUSE', 'disney', 'https://boards.greenhouse.io/disney'),
('Lor', 'GREENHOUSE', 'lor', 'https://boards.greenhouse.io/lor'),
('Flash', 'GREENHOUSE', 'flash', 'https://boards.greenhouse.io/flash'),
('Berelaxspa', 'GREENHOUSE', 'berelaxspa', 'https://boards.greenhouse.io/berelaxspa'),
('Air', 'GREENHOUSE', 'air', 'https://boards.greenhouse.io/air'),
('Cannondale', 'GREENHOUSE', 'cannondale', 'https://boards.greenhouse.io/cannondale'),
('Silicon', 'GREENHOUSE', 'silicon', 'https://boards.greenhouse.io/silicon'),
('Fourstar', 'GREENHOUSE', 'fourstar', 'https://boards.greenhouse.io/fourstar'),
('Prisma', 'GREENHOUSE', 'prisma', 'https://boards.greenhouse.io/prisma'),
('International', 'GREENHOUSE', 'international', 'https://boards.greenhouse.io/international'),
('Beyond', 'GREENHOUSE', 'beyond', 'https://boards.greenhouse.io/beyond'),
('Cais', 'GREENHOUSE', 'cais', 'https://boards.greenhouse.io/cais'),
('Colorado', 'GREENHOUSE', 'colorado', 'https://boards.greenhouse.io/colorado'),
('Spain', 'GREENHOUSE', 'spain', 'https://boards.greenhouse.io/spain'),
('Zoo', 'GREENHOUSE', 'zoo', 'https://boards.greenhouse.io/zoo'),
('Genius', 'GREENHOUSE', 'genius', 'https://boards.greenhouse.io/genius'),
('Aha', 'GREENHOUSE', 'aha', 'https://boards.greenhouse.io/aha'),
('Village', 'GREENHOUSE', 'village', 'https://boards.greenhouse.io/village'),
('Nectar', 'GREENHOUSE', 'nectar', 'https://boards.greenhouse.io/nectar'),
('Lush', 'GREENHOUSE', 'lush', 'https://boards.greenhouse.io/lush'),
('Supreme', 'GREENHOUSE', 'supreme', 'https://boards.greenhouse.io/supreme'),
('Transform', 'GREENHOUSE', 'transform', 'https://boards.greenhouse.io/transform'),
('Alliance', 'GREENHOUSE', 'alliance', 'https://boards.greenhouse.io/alliance'),
('Festival', 'GREENHOUSE', 'festival', 'https://boards.greenhouse.io/festival'),
('Apex', 'GREENHOUSE', 'apex', 'https://boards.greenhouse.io/apex'),
('Kite', 'GREENHOUSE', 'kite', 'https://boards.greenhouse.io/kite'),
('Rga', 'GREENHOUSE', 'rga', 'https://boards.greenhouse.io/rga'),
('Icon', 'GREENHOUSE', 'icon', 'https://boards.greenhouse.io/icon'),
('Rab', 'GREENHOUSE', 'rab', 'https://boards.greenhouse.io/rab'),
('Esri', 'GREENHOUSE', 'esri', 'https://boards.greenhouse.io/esri'),
('Basic', 'GREENHOUSE', 'basic', 'https://boards.greenhouse.io/basic'),
('Place', 'GREENHOUSE', 'place', 'https://boards.greenhouse.io/place'),
('Allied', 'GREENHOUSE', 'allied', 'https://boards.greenhouse.io/allied'),
('Blend', 'GREENHOUSE', 'blend', 'https://boards.greenhouse.io/blend'),
('Selling', 'GREENHOUSE', 'selling', 'https://boards.greenhouse.io/selling'),
('Osmosis', 'GREENHOUSE', 'osmosis', 'https://boards.greenhouse.io/osmosis'),
('Goal', 'GREENHOUSE', 'goal', 'https://boards.greenhouse.io/goal'),
('Map', 'GREENHOUSE', 'map', 'https://boards.greenhouse.io/map'),
('Summer', 'GREENHOUSE', 'summer', 'https://boards.greenhouse.io/summer'),
('Alta', 'GREENHOUSE', 'alta', 'https://boards.greenhouse.io/alta'),
('Maro', 'GREENHOUSE', 'maro', 'https://boards.greenhouse.io/maro'),
('Fourseasons', 'GREENHOUSE', 'fourseasons', 'https://boards.greenhouse.io/fourseasons'),
('Elite', 'GREENHOUSE', 'elite', 'https://boards.greenhouse.io/elite'),
('Ampm', 'GREENHOUSE', 'ampm', 'https://boards.greenhouse.io/ampm'),
('Maestro', 'GREENHOUSE', 'maestro', 'https://boards.greenhouse.io/maestro'),
('Via', 'GREENHOUSE', 'via', 'https://boards.greenhouse.io/via'),
('Ohio', 'GREENHOUSE', 'ohio', 'https://boards.greenhouse.io/ohio'),
('A24', 'GREENHOUSE', 'a24', 'https://boards.greenhouse.io/a24'),
('Alu', 'GREENHOUSE', 'alu', 'https://boards.greenhouse.io/alu'),
('Technology', 'GREENHOUSE', 'technology', 'https://boards.greenhouse.io/technology'),
('Glance', 'GREENHOUSE', 'glance', 'https://boards.greenhouse.io/glance'),
('Tekla', 'GREENHOUSE', 'tekla', 'https://boards.greenhouse.io/tekla'),
('Neu', 'GREENHOUSE', 'neu', 'https://boards.greenhouse.io/neu'),
('System', 'GREENHOUSE', 'system', 'https://boards.greenhouse.io/system'),
('Insurance', 'GREENHOUSE', 'insurance', 'https://boards.greenhouse.io/insurance'),
('Education', 'GREENHOUSE', 'education', 'https://boards.greenhouse.io/education'),
('Harbor', 'GREENHOUSE', 'harbor', 'https://boards.greenhouse.io/harbor'),
('Moltonbrown', 'GREENHOUSE', 'moltonbrown', 'https://boards.greenhouse.io/moltonbrown'),
('Uplift', 'GREENHOUSE', 'uplift', 'https://boards.greenhouse.io/uplift'),
('Pia', 'GREENHOUSE', 'pia', 'https://boards.greenhouse.io/pia'),
('Network', 'GREENHOUSE', 'network', 'https://boards.greenhouse.io/network'),
('Grey', 'GREENHOUSE', 'grey', 'https://boards.greenhouse.io/grey'),
('Lasenza', 'GREENHOUSE', 'lasenza', 'https://boards.greenhouse.io/lasenza'),
('Doc', 'GREENHOUSE', 'doc', 'https://boards.greenhouse.io/doc'),
('Vmax', 'GREENHOUSE', 'vmax', 'https://boards.greenhouse.io/vmax'),
('Pronto', 'GREENHOUSE', 'pronto', 'https://boards.greenhouse.io/pronto'),
('Community', 'GREENHOUSE', 'community', 'https://boards.greenhouse.io/community'),
('Cleo', 'GREENHOUSE', 'cleo', 'https://boards.greenhouse.io/cleo'),
('Trolley', 'GREENHOUSE', 'trolley', 'https://boards.greenhouse.io/trolley'),
('Route', 'GREENHOUSE', 'route', 'https://boards.greenhouse.io/route'),
('Tamara', 'GREENHOUSE', 'tamara', 'https://boards.greenhouse.io/tamara'),
('Pcm', 'GREENHOUSE', 'pcm', 'https://boards.greenhouse.io/pcm'),
('Radar', 'GREENHOUSE', 'radar', 'https://boards.greenhouse.io/radar'),
('Crescent', 'GREENHOUSE', 'crescent', 'https://boards.greenhouse.io/crescent'),
('Impact', 'GREENHOUSE', 'impact', 'https://boards.greenhouse.io/impact'),
('Remedy', 'GREENHOUSE', 'remedy', 'https://boards.greenhouse.io/remedy'),
('Action', 'GREENHOUSE', 'action', 'https://boards.greenhouse.io/action'),
('Axle', 'GREENHOUSE', 'axle', 'https://boards.greenhouse.io/axle'),
('Eve', 'GREENHOUSE', 'eve', 'https://boards.greenhouse.io/eve'),
('Wasabi', 'GREENHOUSE', 'wasabi', 'https://boards.greenhouse.io/wasabi'),
('Zam', 'GREENHOUSE', 'zam', 'https://boards.greenhouse.io/zam'),
('Rehabilitation', 'GREENHOUSE', 'rehabilitation', 'https://boards.greenhouse.io/rehabilitation'),
('Goodwin', 'GREENHOUSE', 'goodwin', 'https://boards.greenhouse.io/goodwin'),
('Trident', 'GREENHOUSE', 'trident', 'https://boards.greenhouse.io/trident'),
('Bird', 'GREENHOUSE', 'bird', 'https://boards.greenhouse.io/bird'),
('Honor', 'GREENHOUSE', 'honor', 'https://boards.greenhouse.io/honor'),
('Inter', 'GREENHOUSE', 'inter', 'https://boards.greenhouse.io/inter'),
('Block', 'GREENHOUSE', 'block', 'https://boards.greenhouse.io/block'),
('Cherry', 'GREENHOUSE', 'cherry', 'https://boards.greenhouse.io/cherry'),
('Fruitful', 'GREENHOUSE', 'fruitful', 'https://boards.greenhouse.io/fruitful'),
('Pulse', 'GREENHOUSE', 'pulse', 'https://boards.greenhouse.io/pulse'),
('Cio', 'GREENHOUSE', 'cio', 'https://boards.greenhouse.io/cio'),
('Edo', 'GREENHOUSE', 'edo', 'https://boards.greenhouse.io/edo'),
('Mercury', 'GREENHOUSE', 'mercury', 'https://boards.greenhouse.io/mercury'),
('Bravo', 'GREENHOUSE', 'bravo', 'https://boards.greenhouse.io/bravo'),
('Jumia', 'GREENHOUSE', 'jumia', 'https://boards.greenhouse.io/jumia'),
('Noble', 'GREENHOUSE', 'noble', 'https://boards.greenhouse.io/noble'),
('Retail', 'GREENHOUSE', 'retail', 'https://boards.greenhouse.io/retail'),
('Ever', 'GREENHOUSE', 'ever', 'https://boards.greenhouse.io/ever'),
('Nice', 'GREENHOUSE', 'nice', 'https://boards.greenhouse.io/nice'),
('Markets', 'GREENHOUSE', 'markets', 'https://boards.greenhouse.io/markets'),
('Emerge', 'GREENHOUSE', 'emerge', 'https://boards.greenhouse.io/emerge'),
('Tca', 'GREENHOUSE', 'tca', 'https://boards.greenhouse.io/tca'),
('Quince', 'GREENHOUSE', 'quince', 'https://boards.greenhouse.io/quince'),
('Des', 'GREENHOUSE', 'des', 'https://boards.greenhouse.io/des'),
('Golf', 'GREENHOUSE', 'golf', 'https://boards.greenhouse.io/golf'),
('Genesis', 'GREENHOUSE', 'genesis', 'https://boards.greenhouse.io/genesis'),
('Technical', 'GREENHOUSE', 'technical', 'https://boards.greenhouse.io/technical'),
('Onyx', 'GREENHOUSE', 'onyx', 'https://boards.greenhouse.io/onyx'),
('Squad', 'GREENHOUSE', 'squad', 'https://boards.greenhouse.io/squad'),
('Purple', 'GREENHOUSE', 'purple', 'https://boards.greenhouse.io/purple'),
('Scotch', 'GREENHOUSE', 'scotch', 'https://boards.greenhouse.io/scotch'),
('Shein', 'GREENHOUSE', 'shein', 'https://boards.greenhouse.io/shein'),
('Essential', 'GREENHOUSE', 'essential', 'https://boards.greenhouse.io/essential'),
('Lincoln', 'GREENHOUSE', 'lincoln', 'https://boards.greenhouse.io/lincoln'),
('Escada', 'GREENHOUSE', 'escada', 'https://boards.greenhouse.io/escada'),
('India', 'GREENHOUSE', 'india', 'https://boards.greenhouse.io/india'),
('Oasis', 'GREENHOUSE', 'oasis', 'https://boards.greenhouse.io/oasis'),
('Escala', 'GREENHOUSE', 'escala', 'https://boards.greenhouse.io/escala'),
('Vts', 'GREENHOUSE', 'vts', 'https://boards.greenhouse.io/vts'),
('Petcare', 'GREENHOUSE', 'petcare', 'https://boards.greenhouse.io/petcare'),
('Vega', 'GREENHOUSE', 'vega', 'https://boards.greenhouse.io/vega'),
('Claros', 'GREENHOUSE', 'claros', 'https://boards.greenhouse.io/claros'),
('Remote', 'GREENHOUSE', 'remote', 'https://boards.greenhouse.io/remote'),
('Byd', 'GREENHOUSE', 'byd', 'https://boards.greenhouse.io/byd'),
('Firstchoice', 'GREENHOUSE', 'firstchoice', 'https://boards.greenhouse.io/firstchoice'),
('Camp', 'GREENHOUSE', 'camp', 'https://boards.greenhouse.io/camp'),
('Greenhouse', 'GREENHOUSE', 'greenhouse', 'https://boards.greenhouse.io/greenhouse')
ON CONFLICT (board_token) DO UPDATE 
SET name = EXCLUDED.name, ats_type = EXCLUDED.ats_type;


-- =========================================================================
-- 3. INSERT: Lever Portals
-- =========================================================================
INSERT INTO companies (name, ats_type, board_token, website_url) VALUES 
('Twodots', 'LEVER', 'twodots', 'https://api.lever.co/v0/postings/twodots'),
('Packagex', 'LEVER', 'packagex', 'https://api.lever.co/v0/postings/packagex'),
('Mindbloom', 'LEVER', 'mindbloom', 'https://api.lever.co/v0/postings/mindbloom'),
('Mrss', 'LEVER', 'mrss', 'https://api.lever.co/v0/postings/mrss'),
('Playplay', 'LEVER', 'playplay', 'https://api.lever.co/v0/postings/playplay'),
('Realworklabs', 'LEVER', 'realworklabs', 'https://api.lever.co/v0/postings/realworklabs'),
('Erpsuccesspartners', 'LEVER', 'erpsuccesspartners', 'https://api.lever.co/v0/postings/erpsuccesspartners'),
('Mixlab', 'LEVER', 'mixlab', 'https://api.lever.co/v0/postings/mixlab'),
('Gardengreens', 'LEVER', 'gardengreens', 'https://api.lever.co/v0/postings/gardengreens'),
('Baunfire', 'LEVER', 'baunfire', 'https://api.lever.co/v0/postings/baunfire'),
('Smartenergy', 'LEVER', 'smartenergy', 'https://api.lever.co/v0/postings/smartenergy'),
('Chargezoom', 'LEVER', 'chargezoom', 'https://api.lever.co/v0/postings/chargezoom'),
('Hightechhigh', 'LEVER', 'hightechhigh', 'https://api.lever.co/v0/postings/hightechhigh'),
('Cyara', 'LEVER', 'cyara', 'https://api.lever.co/v0/postings/cyara'),
('Sure', 'LEVER', 'sure', 'https://api.lever.co/v0/postings/sure'),
('Kubra', 'LEVER', 'kubra', 'https://api.lever.co/v0/postings/kubra'),
('Thinkingbox', 'LEVER', 'thinkingbox', 'https://api.lever.co/v0/postings/thinkingbox'),
('Unifyconsulting', 'LEVER', 'unifyconsulting', 'https://api.lever.co/v0/postings/unifyconsulting'),
('Kavak', 'LEVER', 'kavak', 'https://api.lever.co/v0/postings/kavak'),
('Communityactionhouse', 'LEVER', 'communityactionhouse', 'https://api.lever.co/v0/postings/communityactionhouse'),
('Whiterivertoyota', 'LEVER', 'whiterivertoyota', 'https://api.lever.co/v0/postings/whiterivertoyota'),
('Anzen', 'LEVER', 'anzen', 'https://api.lever.co/v0/postings/anzen'),
('Activetheory', 'LEVER', 'activetheory', 'https://api.lever.co/v0/postings/activetheory'),
('Ceso', 'LEVER', 'ceso', 'https://api.lever.co/v0/postings/ceso'),
('Makipeople', 'LEVER', 'makipeople', 'https://api.lever.co/v0/postings/makipeople'),
('Objective', 'LEVER', 'objective', 'https://api.lever.co/v0/postings/objective'),
('Thinkstermath', 'LEVER', 'thinkstermath', 'https://api.lever.co/v0/postings/thinkstermath'),
('Liatrio', 'LEVER', 'liatrio', 'https://api.lever.co/v0/postings/liatrio'),
('Watchguard', 'LEVER', 'watchguard', 'https://api.lever.co/v0/postings/watchguard'),
('Pachama', 'LEVER', 'pachama', 'https://api.lever.co/v0/postings/pachama'),
('Margueritecaseyfoundation', 'LEVER', 'margueritecaseyfoundation', 'https://api.lever.co/v0/postings/margueritecaseyfoundation'),
('Primatelabs', 'LEVER', 'primatelabs', 'https://api.lever.co/v0/postings/primatelabs'),
('Germanamerican', 'LEVER', 'germanamerican', 'https://api.lever.co/v0/postings/germanamerican'),
('Lumafield', 'LEVER', 'lumafield', 'https://api.lever.co/v0/postings/lumafield'),
('Prolific-machines', 'LEVER', 'prolific-machines', 'https://api.lever.co/v0/postings/prolific-machines'),
('Jaumo', 'LEVER', 'jaumo', 'https://api.lever.co/v0/postings/jaumo'),
('Alector', 'LEVER', 'alector', 'https://api.lever.co/v0/postings/alector'),
('Athletetoathlete', 'LEVER', 'athletetoathlete', 'https://api.lever.co/v0/postings/athletetoathlete'),
('Appfigures', 'LEVER', 'appfigures', 'https://api.lever.co/v0/postings/appfigures'),
('Humata', 'LEVER', 'humata', 'https://api.lever.co/v0/postings/humata'),
('Havenparkcommunities', 'LEVER', 'havenparkcommunities', 'https://api.lever.co/v0/postings/havenparkcommunities'),
('Tildei', 'LEVER', 'tildei', 'https://api.lever.co/v0/postings/tildei'),
('Emitwise', 'LEVER', 'emitwise', 'https://api.lever.co/v0/postings/emitwise'),
('Wisr', 'LEVER', 'wisr', 'https://api.lever.co/v0/postings/wisr'),
('Ethenalabs', 'LEVER', 'ethenalabs', 'https://api.lever.co/v0/postings/ethenalabs'),
('System1', 'LEVER', 'system1', 'https://api.lever.co/v0/postings/system1'),
('Sila', 'LEVER', 'sila', 'https://api.lever.co/v0/postings/sila'),
('Edgeofs', 'LEVER', 'edgeofs', 'https://api.lever.co/v0/postings/edgeofs'),
('Hosco', 'LEVER', 'hosco', 'https://api.lever.co/v0/postings/hosco'),
('Waabi', 'LEVER', 'waabi', 'https://api.lever.co/v0/postings/waabi'),
('Circadiahealth', 'LEVER', 'circadiahealth', 'https://api.lever.co/v0/postings/circadiahealth'),
('Thedispatch', 'LEVER', 'thedispatch', 'https://api.lever.co/v0/postings/thedispatch'),
('Blueorigin', 'LEVER', 'blueorigin', 'https://api.lever.co/v0/postings/blueorigin'),
('Kasheesh', 'LEVER', 'kasheesh', 'https://api.lever.co/v0/postings/kasheesh'),
('Buildingswell', 'LEVER', 'buildingswell', 'https://api.lever.co/v0/postings/buildingswell'),
('Refed', 'LEVER', 'refed', 'https://api.lever.co/v0/postings/refed'),
('Gearset', 'LEVER', 'gearset', 'https://api.lever.co/v0/postings/gearset'),
('Vidsy', 'LEVER', 'vidsy', 'https://api.lever.co/v0/postings/vidsy'),
('Sait', 'LEVER', 'sait', 'https://api.lever.co/v0/postings/sait'),
('Wenvision', 'LEVER', 'wenvision', 'https://api.lever.co/v0/postings/wenvision'),
('Sitetracker', 'LEVER', 'sitetracker', 'https://api.lever.co/v0/postings/sitetracker'),
('Vrchat', 'LEVER', 'vrchat', 'https://api.lever.co/v0/postings/vrchat'),
('Crypto-banter', 'LEVER', 'crypto-banter', 'https://api.lever.co/v0/postings/crypto-banter'),
('Restaurant365', 'LEVER', 'restaurant365', 'https://api.lever.co/v0/postings/restaurant365'),
('Flare', 'LEVER', 'flare', 'https://api.lever.co/v0/postings/flare'),
('Astrus', 'LEVER', 'astrus', 'https://api.lever.co/v0/postings/astrus'),
('Doctrine', 'LEVER', 'doctrine', 'https://api.lever.co/v0/postings/doctrine'),
('Goodleap', 'LEVER', 'goodleap', 'https://api.lever.co/v0/postings/goodleap'),
('Aerostrat', 'LEVER', 'aerostrat', 'https://api.lever.co/v0/postings/aerostrat'),
('Outpacebio', 'LEVER', 'outpacebio', 'https://api.lever.co/v0/postings/outpacebio'),
('Walkme', 'LEVER', 'walkme', 'https://api.lever.co/v0/postings/walkme'),
('Bolster', 'LEVER', 'bolster', 'https://api.lever.co/v0/postings/bolster'),
('Outsight', 'LEVER', 'outsight', 'https://api.lever.co/v0/postings/outsight'),
('Illumination', 'LEVER', 'illumination', 'https://api.lever.co/v0/postings/illumination'),
('Mamamoney', 'LEVER', 'mamamoney', 'https://api.lever.co/v0/postings/mamamoney'),
('Tenncare', 'LEVER', 'tenncare', 'https://api.lever.co/v0/postings/tenncare'),
('Revinate', 'LEVER', 'revinate', 'https://api.lever.co/v0/postings/revinate'),
('Pillartechnology', 'LEVER', 'pillartechnology', 'https://api.lever.co/v0/postings/pillartechnology'),
('Fanatee', 'LEVER', 'fanatee', 'https://api.lever.co/v0/postings/fanatee'),
('Ippon', 'LEVER', 'ippon', 'https://api.lever.co/v0/postings/ippon'),
('Coalescence', 'LEVER', 'coalescence', 'https://api.lever.co/v0/postings/coalescence'),
('Standtogether', 'LEVER', 'standtogether', 'https://api.lever.co/v0/postings/standtogether'),
('Infraservices', 'LEVER', 'infraservices', 'https://api.lever.co/v0/postings/infraservices'),
('Leadershipconnect', 'LEVER', 'leadershipconnect', 'https://api.lever.co/v0/postings/leadershipconnect'),
('Mainspringenergy', 'LEVER', 'mainspringenergy', 'https://api.lever.co/v0/postings/mainspringenergy'),
('Metecs', 'LEVER', 'metecs', 'https://api.lever.co/v0/postings/metecs'),
('Plaid', 'LEVER', 'plaid', 'https://api.lever.co/v0/postings/plaid'),
('Viabill', 'LEVER', 'viabill', 'https://api.lever.co/v0/postings/viabill'),
('Easyagile', 'LEVER', 'easyagile', 'https://api.lever.co/v0/postings/easyagile'),
('Metasite', 'LEVER', 'metasite', 'https://api.lever.co/v0/postings/metasite'),
('Techtalentproject', 'LEVER', 'techtalentproject', 'https://api.lever.co/v0/postings/techtalentproject'),
('Cred', 'LEVER', 'cred', 'https://api.lever.co/v0/postings/cred'),
('Holloway', 'LEVER', 'holloway', 'https://api.lever.co/v0/postings/holloway'),
('Telligen', 'LEVER', 'telligen', 'https://api.lever.co/v0/postings/telligen'),
('Triggerxr', 'LEVER', 'triggerxr', 'https://api.lever.co/v0/postings/triggerxr'),
('Modeln', 'LEVER', 'modeln', 'https://api.lever.co/v0/postings/modeln'),
('Nobody', 'LEVER', 'nobody', 'https://api.lever.co/v0/postings/nobody'),
('Churchatthepark', 'LEVER', 'churchatthepark', 'https://api.lever.co/v0/postings/churchatthepark'),
('Zenitech', 'LEVER', 'zenitech', 'https://api.lever.co/v0/postings/zenitech'),
('Aquarium', 'LEVER', 'aquarium', 'https://api.lever.co/v0/postings/aquarium'),
('Deltaairportconsultants', 'LEVER', 'deltaairportconsultants', 'https://api.lever.co/v0/postings/deltaairportconsultants'),
('Zinovo', 'LEVER', 'zinovo', 'https://api.lever.co/v0/postings/zinovo'),
('Bigblue', 'LEVER', 'bigblue', 'https://api.lever.co/v0/postings/bigblue'),
('Sugarcrm', 'LEVER', 'sugarcrm', 'https://api.lever.co/v0/postings/sugarcrm'),
('Lqdigital', 'LEVER', 'lqdigital', 'https://api.lever.co/v0/postings/lqdigital'),
('Sysdig', 'LEVER', 'sysdig', 'https://api.lever.co/v0/postings/sysdig'),
('Nxtthingrpo', 'LEVER', 'nxtthingrpo', 'https://api.lever.co/v0/postings/nxtthingrpo'),
('Beta', 'LEVER', 'beta', 'https://api.lever.co/v0/postings/beta'),
('Replate', 'LEVER', 'replate', 'https://api.lever.co/v0/postings/replate'),
('Litcolaw', 'LEVER', 'litcolaw', 'https://api.lever.co/v0/postings/litcolaw'),
('Cdcfoundation', 'LEVER', 'cdcfoundation', 'https://api.lever.co/v0/postings/cdcfoundation'),
('Wildlight', 'LEVER', 'wildlight', 'https://api.lever.co/v0/postings/wildlight'),
('Betr', 'LEVER', 'betr', 'https://api.lever.co/v0/postings/betr'),
('Advocate', 'LEVER', 'advocate', 'https://api.lever.co/v0/postings/advocate'),
('Logrocket', 'LEVER', 'logrocket', 'https://api.lever.co/v0/postings/logrocket'),
('Datalabusa', 'LEVER', 'datalabusa', 'https://api.lever.co/v0/postings/datalabusa'),
('Argonaut', 'LEVER', 'argonaut', 'https://api.lever.co/v0/postings/argonaut'),
('Hr-performance', 'LEVER', 'hr-performance', 'https://api.lever.co/v0/postings/hr-performance'),
('Nimbus', 'LEVER', 'nimbus', 'https://api.lever.co/v0/postings/nimbus'),
('Catlabs', 'LEVER', 'catlabs', 'https://api.lever.co/v0/postings/catlabs'),
('Candidate', 'LEVER', 'candidate', 'https://api.lever.co/v0/postings/candidate'),
('Oneup', 'LEVER', 'oneup', 'https://api.lever.co/v0/postings/oneup'),
('Skyboxlabs', 'LEVER', 'skyboxlabs', 'https://api.lever.co/v0/postings/skyboxlabs'),
('Healx', 'LEVER', 'healx', 'https://api.lever.co/v0/postings/healx'),
('Ethree', 'LEVER', 'ethree', 'https://api.lever.co/v0/postings/ethree'),
('Thekrazycouponlady', 'LEVER', 'thekrazycouponlady', 'https://api.lever.co/v0/postings/thekrazycouponlady'),
('Bluelightconsulting', 'LEVER', 'bluelightconsulting', 'https://api.lever.co/v0/postings/bluelightconsulting'),
('Elk-marketing', 'LEVER', 'elk-marketing', 'https://api.lever.co/v0/postings/elk-marketing'),
('Flipster', 'LEVER', 'flipster', 'https://api.lever.co/v0/postings/flipster'),
('Versapay', 'LEVER', 'versapay', 'https://api.lever.co/v0/postings/versapay'),
('Neowiz', 'LEVER', 'neowiz', 'https://api.lever.co/v0/postings/neowiz'),
('Tesorio', 'LEVER', 'tesorio', 'https://api.lever.co/v0/postings/tesorio'),
('Trustarc', 'LEVER', 'trustarc', 'https://api.lever.co/v0/postings/trustarc'),
('Levelup', 'LEVER', 'levelup', 'https://api.lever.co/v0/postings/levelup'),
('Gojob', 'LEVER', 'gojob', 'https://api.lever.co/v0/postings/gojob'),
('Hannaandersson', 'LEVER', 'hannaandersson', 'https://api.lever.co/v0/postings/hannaandersson'),
('Acceldata', 'LEVER', 'acceldata', 'https://api.lever.co/v0/postings/acceldata'),
('Z1tech', 'LEVER', 'z1tech', 'https://api.lever.co/v0/postings/z1tech'),
('Designetics', 'LEVER', 'designetics', 'https://api.lever.co/v0/postings/designetics'),
('Disqo', 'LEVER', 'disqo', 'https://api.lever.co/v0/postings/disqo'),
('Gopuff', 'LEVER', 'gopuff', 'https://api.lever.co/v0/postings/gopuff'),
('Boostie', 'LEVER', 'boostie', 'https://api.lever.co/v0/postings/boostie'),
('Text', 'LEVER', 'text', 'https://api.lever.co/v0/postings/text'),
('Mulhalls', 'LEVER', 'mulhalls', 'https://api.lever.co/v0/postings/mulhalls'),
('Cellares', 'LEVER', 'cellares', 'https://api.lever.co/v0/postings/cellares'),
('Openresearch', 'LEVER', 'openresearch', 'https://api.lever.co/v0/postings/openresearch'),
('Unlikely', 'LEVER', 'unlikely', 'https://api.lever.co/v0/postings/unlikely'),
('Mirego', 'LEVER', 'mirego', 'https://api.lever.co/v0/postings/mirego'),
('Founderscard', 'LEVER', 'founderscard', 'https://api.lever.co/v0/postings/founderscard'),
('Bridge2rwanda', 'LEVER', 'bridge2rwanda', 'https://api.lever.co/v0/postings/bridge2rwanda'),
('Alltourage', 'LEVER', 'alltourage', 'https://api.lever.co/v0/postings/alltourage'),
('Parallelwireless', 'LEVER', 'parallelwireless', 'https://api.lever.co/v0/postings/parallelwireless'),
('Topdesk', 'LEVER', 'topdesk', 'https://api.lever.co/v0/postings/topdesk'),
('Ravensburger-north-america', 'LEVER', 'ravensburger-north-america', 'https://api.lever.co/v0/postings/ravensburger-north-america'),
('Linkedin', 'LEVER', 'linkedin', 'https://api.lever.co/v0/postings/linkedin'),
('Maxpool', 'LEVER', 'maxpool', 'https://api.lever.co/v0/postings/maxpool'),
('Vidrovr', 'LEVER', 'vidrovr', 'https://api.lever.co/v0/postings/vidrovr'),
('Innodata', 'LEVER', 'innodata', 'https://api.lever.co/v0/postings/innodata'),
('Cuningham', 'LEVER', 'cuningham', 'https://api.lever.co/v0/postings/cuningham'),
('Yuno', 'LEVER', 'yuno', 'https://api.lever.co/v0/postings/yuno'),
('Hawthorne-health', 'LEVER', 'hawthorne-health', 'https://api.lever.co/v0/postings/hawthorne-health'),
('Novosfiber', 'LEVER', 'novosfiber', 'https://api.lever.co/v0/postings/novosfiber'),
('Abovelending', 'LEVER', 'abovelending', 'https://api.lever.co/v0/postings/abovelending'),
('Fatetherapeutics', 'LEVER', 'fatetherapeutics', 'https://api.lever.co/v0/postings/fatetherapeutics'),
('Airtm', 'LEVER', 'airtm', 'https://api.lever.co/v0/postings/airtm'),
('Bluesight', 'LEVER', 'bluesight', 'https://api.lever.co/v0/postings/bluesight'),
('Firstup', 'LEVER', 'firstup', 'https://api.lever.co/v0/postings/firstup'),
('Ivani', 'LEVER', 'ivani', 'https://api.lever.co/v0/postings/ivani'),
('Superpedestrian', 'LEVER', 'superpedestrian', 'https://api.lever.co/v0/postings/superpedestrian'),
('Inductivehealth', 'LEVER', 'inductivehealth', 'https://api.lever.co/v0/postings/inductivehealth'),
('Lirvanalabs', 'LEVER', 'lirvanalabs', 'https://api.lever.co/v0/postings/lirvanalabs'),
('Skyways', 'LEVER', 'skyways', 'https://api.lever.co/v0/postings/skyways'),
('Cority', 'LEVER', 'cority', 'https://api.lever.co/v0/postings/cority'),
('State-policy-network', 'LEVER', 'state-policy-network', 'https://api.lever.co/v0/postings/state-policy-network'),
('Buyboxexperts', 'LEVER', 'buyboxexperts', 'https://api.lever.co/v0/postings/buyboxexperts'),
('Aicrete', 'LEVER', 'aicrete', 'https://api.lever.co/v0/postings/aicrete'),
('Conversica', 'LEVER', 'conversica', 'https://api.lever.co/v0/postings/conversica'),
('Jobin', 'LEVER', 'jobin', 'https://api.lever.co/v0/postings/jobin'),
('Bearflagrobotics', 'LEVER', 'bearflagrobotics', 'https://api.lever.co/v0/postings/bearflagrobotics'),
('Beghouconsulting', 'LEVER', 'beghouconsulting', 'https://api.lever.co/v0/postings/beghouconsulting'),
('Kiddom', 'LEVER', 'kiddom', 'https://api.lever.co/v0/postings/kiddom'),
('Omnidian', 'LEVER', 'omnidian', 'https://api.lever.co/v0/postings/omnidian'),
('Form', 'LEVER', 'form', 'https://api.lever.co/v0/postings/form'),
('Marketcircle', 'LEVER', 'marketcircle', 'https://api.lever.co/v0/postings/marketcircle'),
('Crypto', 'LEVER', 'crypto', 'https://api.lever.co/v0/postings/crypto'),
('Blablacar', 'LEVER', 'blablacar', 'https://api.lever.co/v0/postings/blablacar'),
('Tractian', 'LEVER', 'tractian', 'https://api.lever.co/v0/postings/tractian'),
('Poki', 'LEVER', 'poki', 'https://api.lever.co/v0/postings/poki'),
('Computercare', 'LEVER', 'computercare', 'https://api.lever.co/v0/postings/computercare'),
('Valiantys', 'LEVER', 'valiantys', 'https://api.lever.co/v0/postings/valiantys'),
('Challengecharterschools', 'LEVER', 'challengecharterschools', 'https://api.lever.co/v0/postings/challengecharterschools'),
('Modicum', 'LEVER', 'modicum', 'https://api.lever.co/v0/postings/modicum'),
('Layup', 'LEVER', 'layup', 'https://api.lever.co/v0/postings/layup'),
('Doranjones', 'LEVER', 'doranjones', 'https://api.lever.co/v0/postings/doranjones'),
('Newwestern', 'LEVER', 'newwestern', 'https://api.lever.co/v0/postings/newwestern'),
('Explodingkittens', 'LEVER', 'explodingkittens', 'https://api.lever.co/v0/postings/explodingkittens'),
('Princesspolly', 'LEVER', 'princesspolly', 'https://api.lever.co/v0/postings/princesspolly'),
('Kitmanlabs', 'LEVER', 'kitmanlabs', 'https://api.lever.co/v0/postings/kitmanlabs'),
('Intropic', 'LEVER', 'intropic', 'https://api.lever.co/v0/postings/intropic'),
('Valgenesis', 'LEVER', 'valgenesis', 'https://api.lever.co/v0/postings/valgenesis'),
('Dealerware', 'LEVER', 'dealerware', 'https://api.lever.co/v0/postings/dealerware'),
('Spline-design', 'LEVER', 'spline-design', 'https://api.lever.co/v0/postings/spline-design'),
('Winamax', 'LEVER', 'winamax', 'https://api.lever.co/v0/postings/winamax'),
('Netvirta', 'LEVER', 'netvirta', 'https://api.lever.co/v0/postings/netvirta'),
('Binance', 'LEVER', 'binance', 'https://api.lever.co/v0/postings/binance'),
('Wgsn', 'LEVER', 'wgsn', 'https://api.lever.co/v0/postings/wgsn'),
('Zerotier', 'LEVER', 'zerotier', 'https://api.lever.co/v0/postings/zerotier'),
('Levelai', 'LEVER', 'levelai', 'https://api.lever.co/v0/postings/levelai'),
('Automatiq', 'LEVER', 'automatiq', 'https://api.lever.co/v0/postings/automatiq'),
('Avalerehealth', 'LEVER', 'avalerehealth', 'https://api.lever.co/v0/postings/avalerehealth'),
('2brains', 'LEVER', '2brains', 'https://api.lever.co/v0/postings/2brains'),
('Aledade', 'LEVER', 'aledade', 'https://api.lever.co/v0/postings/aledade'),
('Aperio-philanthropy', 'LEVER', 'aperio-philanthropy', 'https://api.lever.co/v0/postings/aperio-philanthropy'),
('Grantstreet', 'LEVER', 'grantstreet', 'https://api.lever.co/v0/postings/grantstreet'),
('Summitwashholdings', 'LEVER', 'summitwashholdings', 'https://api.lever.co/v0/postings/summitwashholdings'),
('Bestmile', 'LEVER', 'bestmile', 'https://api.lever.co/v0/postings/bestmile'),
('Envelio', 'LEVER', 'envelio', 'https://api.lever.co/v0/postings/envelio'),
('Fullyvested', 'LEVER', 'fullyvested', 'https://api.lever.co/v0/postings/fullyvested'),
('Waitwhat', 'LEVER', 'waitwhat', 'https://api.lever.co/v0/postings/waitwhat'),
('Badgermapping', 'LEVER', 'badgermapping', 'https://api.lever.co/v0/postings/badgermapping'),
('Lever', 'LEVER', 'lever', 'https://api.lever.co/v0/postings/lever'),
('Gridware', 'LEVER', 'gridware', 'https://api.lever.co/v0/postings/gridware'),
('Triallibrary', 'LEVER', 'triallibrary', 'https://api.lever.co/v0/postings/triallibrary'),
('Certifyos', 'LEVER', 'certifyos', 'https://api.lever.co/v0/postings/certifyos'),
('Trainsweateat', 'LEVER', 'trainsweateat', 'https://api.lever.co/v0/postings/trainsweateat'),
('Digitalfish', 'LEVER', 'digitalfish', 'https://api.lever.co/v0/postings/digitalfish'),
('Angel', 'LEVER', 'angel', 'https://api.lever.co/v0/postings/angel'),
('Apax', 'LEVER', 'apax', 'https://api.lever.co/v0/postings/apax'),
('Bhhc', 'LEVER', 'bhhc', 'https://api.lever.co/v0/postings/bhhc'),
('Avante', 'LEVER', 'avante', 'https://api.lever.co/v0/postings/avante'),
('Wilburlabs', 'LEVER', 'wilburlabs', 'https://api.lever.co/v0/postings/wilburlabs'),
('Ibility', 'LEVER', 'ibility', 'https://api.lever.co/v0/postings/ibility'),
('Culturekings', 'LEVER', 'culturekings', 'https://api.lever.co/v0/postings/culturekings'),
('Treering', 'LEVER', 'treering', 'https://api.lever.co/v0/postings/treering'),
('Tdthornton', 'LEVER', 'tdthornton', 'https://api.lever.co/v0/postings/tdthornton'),
('Spear-ai', 'LEVER', 'spear-ai', 'https://api.lever.co/v0/postings/spear-ai'),
('Lumeto', 'LEVER', 'lumeto', 'https://api.lever.co/v0/postings/lumeto'),
('Gauntlet', 'LEVER', 'gauntlet', 'https://api.lever.co/v0/postings/gauntlet'),
('Girlswhocode', 'LEVER', 'girlswhocode', 'https://api.lever.co/v0/postings/girlswhocode'),
('Arrivelogistics', 'LEVER', 'arrivelogistics', 'https://api.lever.co/v0/postings/arrivelogistics'),
('Whiterabbit', 'LEVER', 'whiterabbit', 'https://api.lever.co/v0/postings/whiterabbit'),
('Anode', 'LEVER', 'anode', 'https://api.lever.co/v0/postings/anode'),
('Blueland', 'LEVER', 'blueland', 'https://api.lever.co/v0/postings/blueland'),
('O-p-e-n', 'LEVER', 'o-p-e-n', 'https://api.lever.co/v0/postings/o-p-e-n'),
('Vergesense', 'LEVER', 'vergesense', 'https://api.lever.co/v0/postings/vergesense'),
('Kapwing', 'LEVER', 'kapwing', 'https://api.lever.co/v0/postings/kapwing'),
('Loftorbital', 'LEVER', 'loftorbital', 'https://api.lever.co/v0/postings/loftorbital'),
('Ttecdigital', 'LEVER', 'ttecdigital', 'https://api.lever.co/v0/postings/ttecdigital'),
('Superside', 'LEVER', 'superside', 'https://api.lever.co/v0/postings/superside'),
('Hopeservices', 'LEVER', 'hopeservices', 'https://api.lever.co/v0/postings/hopeservices'),
('Qualdoc', 'LEVER', 'qualdoc', 'https://api.lever.co/v0/postings/qualdoc'),
('Beedie', 'LEVER', 'beedie', 'https://api.lever.co/v0/postings/beedie'),
('Concurrency', 'LEVER', 'concurrency', 'https://api.lever.co/v0/postings/concurrency'),
('Manifest', 'LEVER', 'manifest', 'https://api.lever.co/v0/postings/manifest'),
('Apcoholdings', 'LEVER', 'apcoholdings', 'https://api.lever.co/v0/postings/apcoholdings'),
('Protectenvironmental', 'LEVER', 'protectenvironmental', 'https://api.lever.co/v0/postings/protectenvironmental'),
('Sageviewadvisory', 'LEVER', 'sageviewadvisory', 'https://api.lever.co/v0/postings/sageviewadvisory'),
('Sophos', 'LEVER', 'sophos', 'https://api.lever.co/v0/postings/sophos'),
('Makpar', 'LEVER', 'makpar', 'https://api.lever.co/v0/postings/makpar'),
('Velo3d', 'LEVER', 'velo3d', 'https://api.lever.co/v0/postings/velo3d'),
('Vida', 'LEVER', 'vida', 'https://api.lever.co/v0/postings/vida'),
('Outlast', 'LEVER', 'outlast', 'https://api.lever.co/v0/postings/outlast'),
('Vital-software', 'LEVER', 'vital-software', 'https://api.lever.co/v0/postings/vital-software'),
('Payactiv', 'LEVER', 'payactiv', 'https://api.lever.co/v0/postings/payactiv'),
('Trueplatform', 'LEVER', 'trueplatform', 'https://api.lever.co/v0/postings/trueplatform'),
('Finfit', 'LEVER', 'finfit', 'https://api.lever.co/v0/postings/finfit'),
('Gatorbio', 'LEVER', 'gatorbio', 'https://api.lever.co/v0/postings/gatorbio'),
('Influur', 'LEVER', 'influur', 'https://api.lever.co/v0/postings/influur'),
('Fintual', 'LEVER', 'fintual', 'https://api.lever.co/v0/postings/fintual'),
('Procept-biorobotics', 'LEVER', 'procept-biorobotics', 'https://api.lever.co/v0/postings/procept-biorobotics'),
('Myvest', 'LEVER', 'myvest', 'https://api.lever.co/v0/postings/myvest'),
('Futo', 'LEVER', 'futo', 'https://api.lever.co/v0/postings/futo'),
('Companial', 'LEVER', 'companial', 'https://api.lever.co/v0/postings/companial'),
('Fixinssoulkitchen', 'LEVER', 'fixinssoulkitchen', 'https://api.lever.co/v0/postings/fixinssoulkitchen'),
('Tribe-payments', 'LEVER', 'tribe-payments', 'https://api.lever.co/v0/postings/tribe-payments'),
('Stackhawk', 'LEVER', 'stackhawk', 'https://api.lever.co/v0/postings/stackhawk'),
('Lever-for-change', 'LEVER', 'lever-for-change', 'https://api.lever.co/v0/postings/lever-for-change'),
('Catalist', 'LEVER', 'catalist', 'https://api.lever.co/v0/postings/catalist'),
('Maxmind', 'LEVER', 'maxmind', 'https://api.lever.co/v0/postings/maxmind'),
('Buckmason', 'LEVER', 'buckmason', 'https://api.lever.co/v0/postings/buckmason'),
('Navisite', 'LEVER', 'navisite', 'https://api.lever.co/v0/postings/navisite'),
('Appletreedental', 'LEVER', 'appletreedental', 'https://api.lever.co/v0/postings/appletreedental'),
('Automatic-leasing-service', 'LEVER', 'automatic-leasing-service', 'https://api.lever.co/v0/postings/automatic-leasing-service'),
('Happyco', 'LEVER', 'happyco', 'https://api.lever.co/v0/postings/happyco'),
('Clari', 'LEVER', 'clari', 'https://api.lever.co/v0/postings/clari'),
('Stardog', 'LEVER', 'stardog', 'https://api.lever.co/v0/postings/stardog'),
('Brighthire', 'LEVER', 'brighthire', 'https://api.lever.co/v0/postings/brighthire'),
('Phoenixtechnologies', 'LEVER', 'phoenixtechnologies', 'https://api.lever.co/v0/postings/phoenixtechnologies'),
('Soraschools', 'LEVER', 'soraschools', 'https://api.lever.co/v0/postings/soraschools'),
('Sierraclub', 'LEVER', 'sierraclub', 'https://api.lever.co/v0/postings/sierraclub'),
('Pipedream', 'LEVER', 'pipedream', 'https://api.lever.co/v0/postings/pipedream'),
('Kixie', 'LEVER', 'kixie', 'https://api.lever.co/v0/postings/kixie'),
('Ip-plus-consulting', 'LEVER', 'ip-plus-consulting', 'https://api.lever.co/v0/postings/ip-plus-consulting'),
('Loblawagency', 'LEVER', 'loblawagency', 'https://api.lever.co/v0/postings/loblawagency'),
('Toku', 'LEVER', 'toku', 'https://api.lever.co/v0/postings/toku'),
('Pocketfm', 'LEVER', 'pocketfm', 'https://api.lever.co/v0/postings/pocketfm'),
('Falcon', 'LEVER', 'falcon', 'https://api.lever.co/v0/postings/falcon'),
('Yonexusa', 'LEVER', 'yonexusa', 'https://api.lever.co/v0/postings/yonexusa'),
('Catalate', 'LEVER', 'catalate', 'https://api.lever.co/v0/postings/catalate'),
('Playco', 'LEVER', 'playco', 'https://api.lever.co/v0/postings/playco'),
('Velocityglobal', 'LEVER', 'velocityglobal', 'https://api.lever.co/v0/postings/velocityglobal'),
('Sarmal', 'LEVER', 'sarmal', 'https://api.lever.co/v0/postings/sarmal'),
('Employ', 'LEVER', 'employ', 'https://api.lever.co/v0/postings/employ'),
('Valdera', 'LEVER', 'valdera', 'https://api.lever.co/v0/postings/valdera'),
('Incorta', 'LEVER', 'incorta', 'https://api.lever.co/v0/postings/incorta'),
('Aicamp', 'LEVER', 'aicamp', 'https://api.lever.co/v0/postings/aicamp'),
('Kasada', 'LEVER', 'kasada', 'https://api.lever.co/v0/postings/kasada'),
('Harmonicdesign', 'LEVER', 'harmonicdesign', 'https://api.lever.co/v0/postings/harmonicdesign'),
('Picklerobot', 'LEVER', 'picklerobot', 'https://api.lever.co/v0/postings/picklerobot'),
('Emergence', 'LEVER', 'emergence', 'https://api.lever.co/v0/postings/emergence'),
('Commonlit', 'LEVER', 'commonlit', 'https://api.lever.co/v0/postings/commonlit'),
('Redbee', 'LEVER', 'redbee', 'https://api.lever.co/v0/postings/redbee'),
('Marcusgrahamproject', 'LEVER', 'marcusgrahamproject', 'https://api.lever.co/v0/postings/marcusgrahamproject'),
('Stradaeducation', 'LEVER', 'stradaeducation', 'https://api.lever.co/v0/postings/stradaeducation'),
('Ordr', 'LEVER', 'ordr', 'https://api.lever.co/v0/postings/ordr'),
('Pushsecurity', 'LEVER', 'pushsecurity', 'https://api.lever.co/v0/postings/pushsecurity'),
('Roebuck-staffing', 'LEVER', 'roebuck-staffing', 'https://api.lever.co/v0/postings/roebuck-staffing'),
('Aragon', 'LEVER', 'aragon', 'https://api.lever.co/v0/postings/aragon'),
('Sapiosciences', 'LEVER', 'sapiosciences', 'https://api.lever.co/v0/postings/sapiosciences'),
('Rillet', 'LEVER', 'rillet', 'https://api.lever.co/v0/postings/rillet'),
('Williamsburglearning', 'LEVER', 'williamsburglearning', 'https://api.lever.co/v0/postings/williamsburglearning'),
('Agile-defense', 'LEVER', 'agile-defense', 'https://api.lever.co/v0/postings/agile-defense'),
('Waveapps', 'LEVER', 'waveapps', 'https://api.lever.co/v0/postings/waveapps'),
('Otilumionics', 'LEVER', 'otilumionics', 'https://api.lever.co/v0/postings/otilumionics'),
('Engine', 'LEVER', 'engine', 'https://api.lever.co/v0/postings/engine'),
('Next-decade', 'LEVER', 'next-decade', 'https://api.lever.co/v0/postings/next-decade'),
('Bizaway', 'LEVER', 'bizaway', 'https://api.lever.co/v0/postings/bizaway'),
('Tenna', 'LEVER', 'tenna', 'https://api.lever.co/v0/postings/tenna'),
('Pt78', 'LEVER', 'pt78', 'https://api.lever.co/v0/postings/pt78'),
('The-sia-foundation', 'LEVER', 'the-sia-foundation', 'https://api.lever.co/v0/postings/the-sia-foundation'),
('Auxia', 'LEVER', 'auxia', 'https://api.lever.co/v0/postings/auxia'),
('Pavementcoffee', 'LEVER', 'pavementcoffee', 'https://api.lever.co/v0/postings/pavementcoffee'),
('Gynesonics', 'LEVER', 'gynesonics', 'https://api.lever.co/v0/postings/gynesonics'),
('Tala', 'LEVER', 'tala', 'https://api.lever.co/v0/postings/tala'),
('Pigment', 'LEVER', 'pigment', 'https://api.lever.co/v0/postings/pigment'),
('Ezcater', 'LEVER', 'ezcater', 'https://api.lever.co/v0/postings/ezcater'),
('Warmly', 'LEVER', 'warmly', 'https://api.lever.co/v0/postings/warmly'),
('Brainner', 'LEVER', 'brainner', 'https://api.lever.co/v0/postings/brainner'),
('Nielsen', 'LEVER', 'nielsen', 'https://api.lever.co/v0/postings/nielsen'),
('Superannotate', 'LEVER', 'superannotate', 'https://api.lever.co/v0/postings/superannotate'),
('Sofarsounds', 'LEVER', 'sofarsounds', 'https://api.lever.co/v0/postings/sofarsounds'),
('Aeva', 'LEVER', 'aeva', 'https://api.lever.co/v0/postings/aeva'),
('Loadsmart', 'LEVER', 'loadsmart', 'https://api.lever.co/v0/postings/loadsmart'),
('Brandknew', 'LEVER', 'brandknew', 'https://api.lever.co/v0/postings/brandknew'),
('Techery', 'LEVER', 'techery', 'https://api.lever.co/v0/postings/techery'),
('Dronedeploy', 'LEVER', 'dronedeploy', 'https://api.lever.co/v0/postings/dronedeploy'),
('Espace', 'LEVER', 'espace', 'https://api.lever.co/v0/postings/espace'),
('Elroyair', 'LEVER', 'elroyair', 'https://api.lever.co/v0/postings/elroyair'),
('Scheduleengine', 'LEVER', 'scheduleengine', 'https://api.lever.co/v0/postings/scheduleengine'),
('Gravisrobotics', 'LEVER', 'gravisrobotics', 'https://api.lever.co/v0/postings/gravisrobotics'),
('Protolabs', 'LEVER', 'protolabs', 'https://api.lever.co/v0/postings/protolabs'),
('Planner5d', 'LEVER', 'planner5d', 'https://api.lever.co/v0/postings/planner5d'),
('Soundhr', 'LEVER', 'soundhr', 'https://api.lever.co/v0/postings/soundhr'),
('Dexterity', 'LEVER', 'dexterity', 'https://api.lever.co/v0/postings/dexterity'),
('Neon', 'LEVER', 'neon', 'https://api.lever.co/v0/postings/neon'),
('Rapiddeploy', 'LEVER', 'rapiddeploy', 'https://api.lever.co/v0/postings/rapiddeploy'),
('Splend', 'LEVER', 'splend', 'https://api.lever.co/v0/postings/splend'),
('Cignys', 'LEVER', 'cignys', 'https://api.lever.co/v0/postings/cignys'),
('Revefi', 'LEVER', 'revefi', 'https://api.lever.co/v0/postings/revefi'),
('Openx', 'LEVER', 'openx', 'https://api.lever.co/v0/postings/openx'),
('Simulmedia', 'LEVER', 'simulmedia', 'https://api.lever.co/v0/postings/simulmedia'),
('Emilyslist', 'LEVER', 'emilyslist', 'https://api.lever.co/v0/postings/emilyslist'),
('Rover', 'LEVER', 'rover', 'https://api.lever.co/v0/postings/rover'),
('Coinmarketcap', 'LEVER', 'coinmarketcap', 'https://api.lever.co/v0/postings/coinmarketcap'),
('Qonto', 'LEVER', 'qonto', 'https://api.lever.co/v0/postings/qonto'),
('Reveneer', 'LEVER', 'reveneer', 'https://api.lever.co/v0/postings/reveneer'),
('Joynbio', 'LEVER', 'joynbio', 'https://api.lever.co/v0/postings/joynbio'),
('Superstate', 'LEVER', 'superstate', 'https://api.lever.co/v0/postings/superstate'),
('Toptal', 'LEVER', 'toptal', 'https://api.lever.co/v0/postings/toptal'),
('Rocketpartners', 'LEVER', 'rocketpartners', 'https://api.lever.co/v0/postings/rocketpartners'),
('Farm-ng', 'LEVER', 'farm-ng', 'https://api.lever.co/v0/postings/farm-ng'),
('Ecosystem', 'LEVER', 'ecosystem', 'https://api.lever.co/v0/postings/ecosystem'),
('Mactores', 'LEVER', 'mactores', 'https://api.lever.co/v0/postings/mactores'),
('Tonsser', 'LEVER', 'tonsser', 'https://api.lever.co/v0/postings/tonsser'),
('Visioninvest', 'LEVER', 'visioninvest', 'https://api.lever.co/v0/postings/visioninvest'),
('Torchdental', 'LEVER', 'torchdental', 'https://api.lever.co/v0/postings/torchdental'),
('Oddin', 'LEVER', 'oddin', 'https://api.lever.co/v0/postings/oddin'),
('Our-place', 'LEVER', 'our-place', 'https://api.lever.co/v0/postings/our-place'),
('Microventures', 'LEVER', 'microventures', 'https://api.lever.co/v0/postings/microventures'),
('Normalyze', 'LEVER', 'normalyze', 'https://api.lever.co/v0/postings/normalyze'),
('Sensefinance', 'LEVER', 'sensefinance', 'https://api.lever.co/v0/postings/sensefinance'),
('Pozy', 'LEVER', 'pozy', 'https://api.lever.co/v0/postings/pozy'),
('Projectkittyhawk', 'LEVER', 'projectkittyhawk', 'https://api.lever.co/v0/postings/projectkittyhawk'),
('Boxlunch', 'LEVER', 'boxlunch', 'https://api.lever.co/v0/postings/boxlunch'),
('Dealmaker', 'LEVER', 'dealmaker', 'https://api.lever.co/v0/postings/dealmaker'),
('Canditech', 'LEVER', 'canditech', 'https://api.lever.co/v0/postings/canditech'),
('Roy-cooper', 'LEVER', 'roy-cooper', 'https://api.lever.co/v0/postings/roy-cooper'),
('Gamma', 'LEVER', 'gamma', 'https://api.lever.co/v0/postings/gamma'),
('Horizon', 'LEVER', 'horizon', 'https://api.lever.co/v0/postings/horizon'),
('Rivr', 'LEVER', 'rivr', 'https://api.lever.co/v0/postings/rivr'),
('Unusual', 'LEVER', 'unusual', 'https://api.lever.co/v0/postings/unusual'),
('Therealdeal', 'LEVER', 'therealdeal', 'https://api.lever.co/v0/postings/therealdeal'),
('Planettechnologies', 'LEVER', 'planettechnologies', 'https://api.lever.co/v0/postings/planettechnologies'),
('Agiliway', 'LEVER', 'agiliway', 'https://api.lever.co/v0/postings/agiliway'),
('Morningbrew', 'LEVER', 'morningbrew', 'https://api.lever.co/v0/postings/morningbrew'),
('Project-healthy-minds', 'LEVER', 'project-healthy-minds', 'https://api.lever.co/v0/postings/project-healthy-minds'),
('Silverbackstrategies', 'LEVER', 'silverbackstrategies', 'https://api.lever.co/v0/postings/silverbackstrategies'),
('Hawaiianhost', 'LEVER', 'hawaiianhost', 'https://api.lever.co/v0/postings/hawaiianhost'),
('Verity', 'LEVER', 'verity', 'https://api.lever.co/v0/postings/verity'),
('Terminus', 'LEVER', 'terminus', 'https://api.lever.co/v0/postings/terminus'),
('Uprightproject', 'LEVER', 'uprightproject', 'https://api.lever.co/v0/postings/uprightproject'),
('Intrepidcollegeprep', 'LEVER', 'intrepidcollegeprep', 'https://api.lever.co/v0/postings/intrepidcollegeprep'),
('Artbio', 'LEVER', 'artbio', 'https://api.lever.co/v0/postings/artbio'),
('Theodo', 'LEVER', 'theodo', 'https://api.lever.co/v0/postings/theodo'),
('Npowermedicine', 'LEVER', 'npowermedicine', 'https://api.lever.co/v0/postings/npowermedicine'),
('Highmatch', 'LEVER', 'highmatch', 'https://api.lever.co/v0/postings/highmatch'),
('Biointellisense', 'LEVER', 'biointellisense', 'https://api.lever.co/v0/postings/biointellisense'),
('Disher', 'LEVER', 'disher', 'https://api.lever.co/v0/postings/disher'),
('Silicon-quantum-computing', 'LEVER', 'silicon-quantum-computing', 'https://api.lever.co/v0/postings/silicon-quantum-computing'),
('Regenxbio', 'LEVER', 'regenxbio', 'https://api.lever.co/v0/postings/regenxbio'),
('Ottertune', 'LEVER', 'ottertune', 'https://api.lever.co/v0/postings/ottertune'),
('Mindful', 'LEVER', 'mindful', 'https://api.lever.co/v0/postings/mindful'),
('Commoncause', 'LEVER', 'commoncause', 'https://api.lever.co/v0/postings/commoncause'),
('Braviantholdings', 'LEVER', 'braviantholdings', 'https://api.lever.co/v0/postings/braviantholdings'),
('Moonsong-labs', 'LEVER', 'moonsong-labs', 'https://api.lever.co/v0/postings/moonsong-labs'),
('Ravio', 'LEVER', 'ravio', 'https://api.lever.co/v0/postings/ravio'),
('Spiria', 'LEVER', 'spiria', 'https://api.lever.co/v0/postings/spiria'),
('Viaseparations', 'LEVER', 'viaseparations', 'https://api.lever.co/v0/postings/viaseparations'),
('Richards-services', 'LEVER', 'richards-services', 'https://api.lever.co/v0/postings/richards-services'),
('Deputy', 'LEVER', 'deputy', 'https://api.lever.co/v0/postings/deputy'),
('Onepointlogistics', 'LEVER', 'onepointlogistics', 'https://api.lever.co/v0/postings/onepointlogistics'),
('Rocketcommunications', 'LEVER', 'rocketcommunications', 'https://api.lever.co/v0/postings/rocketcommunications'),
('Qloo', 'LEVER', 'qloo', 'https://api.lever.co/v0/postings/qloo'),
('Mirai-foods', 'LEVER', 'mirai-foods', 'https://api.lever.co/v0/postings/mirai-foods'),
('Lalamove', 'LEVER', 'lalamove', 'https://api.lever.co/v0/postings/lalamove'),
('Ansatzcapital', 'LEVER', 'ansatzcapital', 'https://api.lever.co/v0/postings/ansatzcapital'),
('Moltenindustries', 'LEVER', 'moltenindustries', 'https://api.lever.co/v0/postings/moltenindustries'),
('Barraiser', 'LEVER', 'barraiser', 'https://api.lever.co/v0/postings/barraiser'),
('Deepersignals', 'LEVER', 'deepersignals', 'https://api.lever.co/v0/postings/deepersignals'),
('Duetti', 'LEVER', 'duetti', 'https://api.lever.co/v0/postings/duetti'),
('Listo', 'LEVER', 'listo', 'https://api.lever.co/v0/postings/listo'),
('Givewell', 'LEVER', 'givewell', 'https://api.lever.co/v0/postings/givewell'),
('Fantasy', 'LEVER', 'fantasy', 'https://api.lever.co/v0/postings/fantasy'),
('Chaoslabs', 'LEVER', 'chaoslabs', 'https://api.lever.co/v0/postings/chaoslabs'),
('Flatfile', 'LEVER', 'flatfile', 'https://api.lever.co/v0/postings/flatfile'),
('Apex-paramedics', 'LEVER', 'apex-paramedics', 'https://api.lever.co/v0/postings/apex-paramedics'),
('Eleks', 'LEVER', 'eleks', 'https://api.lever.co/v0/postings/eleks'),
('Contentsquare', 'LEVER', 'contentsquare', 'https://api.lever.co/v0/postings/contentsquare'),
('5amventures', 'LEVER', '5amventures', 'https://api.lever.co/v0/postings/5amventures'),
('Launchsquad', 'LEVER', 'launchsquad', 'https://api.lever.co/v0/postings/launchsquad'),
('Textnow', 'LEVER', 'textnow', 'https://api.lever.co/v0/postings/textnow'),
('Parcelvision', 'LEVER', 'parcelvision', 'https://api.lever.co/v0/postings/parcelvision'),
('Mechanicalorchard', 'LEVER', 'mechanicalorchard', 'https://api.lever.co/v0/postings/mechanicalorchard'),
('Rainfocus', 'LEVER', 'rainfocus', 'https://api.lever.co/v0/postings/rainfocus'),
('4front', 'LEVER', '4front', 'https://api.lever.co/v0/postings/4front'),
('Ansira', 'LEVER', 'ansira', 'https://api.lever.co/v0/postings/ansira'),
('Gatchealth', 'LEVER', 'gatchealth', 'https://api.lever.co/v0/postings/gatchealth'),
('Trgdevelopment', 'LEVER', 'trgdevelopment', 'https://api.lever.co/v0/postings/trgdevelopment'),
('Endpointclinical', 'LEVER', 'endpointclinical', 'https://api.lever.co/v0/postings/endpointclinical'),
('Pendulum', 'LEVER', 'pendulum', 'https://api.lever.co/v0/postings/pendulum'),
('Autofi', 'LEVER', 'autofi', 'https://api.lever.co/v0/postings/autofi'),
('Includedhealth', 'LEVER', 'includedhealth', 'https://api.lever.co/v0/postings/includedhealth'),
('Thinkahead', 'LEVER', 'thinkahead', 'https://api.lever.co/v0/postings/thinkahead'),
('Keboola', 'LEVER', 'keboola', 'https://api.lever.co/v0/postings/keboola'),
('Tali-ai', 'LEVER', 'tali-ai', 'https://api.lever.co/v0/postings/tali-ai'),
('Resilientco', 'LEVER', 'resilientco', 'https://api.lever.co/v0/postings/resilientco'),
('Epsilon3', 'LEVER', 'epsilon3', 'https://api.lever.co/v0/postings/epsilon3'),
('Quantlane', 'LEVER', 'quantlane', 'https://api.lever.co/v0/postings/quantlane'),
('Retired', 'LEVER', 'retired', 'https://api.lever.co/v0/postings/retired'),
('Lyrebirdstudio', 'LEVER', 'lyrebirdstudio', 'https://api.lever.co/v0/postings/lyrebirdstudio'),
('Loganpm', 'LEVER', 'loganpm', 'https://api.lever.co/v0/postings/loganpm'),
('Ekimetrics', 'LEVER', 'ekimetrics', 'https://api.lever.co/v0/postings/ekimetrics'),
('Modernlife', 'LEVER', 'modernlife', 'https://api.lever.co/v0/postings/modernlife'),
('3jane', 'LEVER', '3jane', 'https://api.lever.co/v0/postings/3jane'),
('Nibiru', 'LEVER', 'nibiru', 'https://api.lever.co/v0/postings/nibiru'),
('Bhvr', 'LEVER', 'bhvr', 'https://api.lever.co/v0/postings/bhvr'),
('Podchaser', 'LEVER', 'podchaser', 'https://api.lever.co/v0/postings/podchaser'),
('Apolloresearch', 'LEVER', 'apolloresearch', 'https://api.lever.co/v0/postings/apolloresearch'),
('Far-ai', 'LEVER', 'far-ai', 'https://api.lever.co/v0/postings/far-ai'),
('Vohra', 'LEVER', 'vohra', 'https://api.lever.co/v0/postings/vohra'),
('Revenueanalytics', 'LEVER', 'revenueanalytics', 'https://api.lever.co/v0/postings/revenueanalytics'),
('Freedompay', 'LEVER', 'freedompay', 'https://api.lever.co/v0/postings/freedompay'),
('Plume', 'LEVER', 'plume', 'https://api.lever.co/v0/postings/plume'),
('Anchorage', 'LEVER', 'anchorage', 'https://api.lever.co/v0/postings/anchorage'),
('Demo', 'LEVER', 'demo', 'https://api.lever.co/v0/postings/demo'),
('Cybourn', 'LEVER', 'cybourn', 'https://api.lever.co/v0/postings/cybourn'),
('Gausslabs', 'LEVER', 'gausslabs', 'https://api.lever.co/v0/postings/gausslabs'),
('Systemex', 'LEVER', 'systemex', 'https://api.lever.co/v0/postings/systemex'),
('Promiserobotics', 'LEVER', 'promiserobotics', 'https://api.lever.co/v0/postings/promiserobotics'),
('Ledger', 'LEVER', 'ledger', 'https://api.lever.co/v0/postings/ledger'),
('Featurex', 'LEVER', 'featurex', 'https://api.lever.co/v0/postings/featurex'),
('Firstmanhattan', 'LEVER', 'firstmanhattan', 'https://api.lever.co/v0/postings/firstmanhattan'),
('Emilabs', 'LEVER', 'emilabs', 'https://api.lever.co/v0/postings/emilabs'),
('Filevine', 'LEVER', 'filevine', 'https://api.lever.co/v0/postings/filevine'),
('Cprime', 'LEVER', 'cprime', 'https://api.lever.co/v0/postings/cprime'),
('Hellotickets', 'LEVER', 'hellotickets', 'https://api.lever.co/v0/postings/hellotickets'),
('Azul', 'LEVER', 'azul', 'https://api.lever.co/v0/postings/azul'),
('Caremessage', 'LEVER', 'caremessage', 'https://api.lever.co/v0/postings/caremessage'),
('Risealliance', 'LEVER', 'risealliance', 'https://api.lever.co/v0/postings/risealliance'),
('Procreate', 'LEVER', 'procreate', 'https://api.lever.co/v0/postings/procreate'),
('Portpro', 'LEVER', 'portpro', 'https://api.lever.co/v0/postings/portpro'),
('Imentor', 'LEVER', 'imentor', 'https://api.lever.co/v0/postings/imentor'),
('Controlup', 'LEVER', 'controlup', 'https://api.lever.co/v0/postings/controlup'),
('Orbaerospace', 'LEVER', 'orbaerospace', 'https://api.lever.co/v0/postings/orbaerospace'),
('Dnagenotek', 'LEVER', 'dnagenotek', 'https://api.lever.co/v0/postings/dnagenotek'),
('Stackblitz', 'LEVER', 'stackblitz', 'https://api.lever.co/v0/postings/stackblitz'),
('Wisdomtree', 'LEVER', 'wisdomtree', 'https://api.lever.co/v0/postings/wisdomtree'),
('Reviverx', 'LEVER', 'reviverx', 'https://api.lever.co/v0/postings/reviverx'),
('Pearpop', 'LEVER', 'pearpop', 'https://api.lever.co/v0/postings/pearpop'),
('Atomi', 'LEVER', 'atomi', 'https://api.lever.co/v0/postings/atomi'),
('Bloom', 'LEVER', 'bloom', 'https://api.lever.co/v0/postings/bloom'),
('Qrypt', 'LEVER', 'qrypt', 'https://api.lever.co/v0/postings/qrypt'),
('Swissborg', 'LEVER', 'swissborg', 'https://api.lever.co/v0/postings/swissborg'),
('Wahi', 'LEVER', 'wahi', 'https://api.lever.co/v0/postings/wahi'),
('Remedyproductstudio', 'LEVER', 'remedyproductstudio', 'https://api.lever.co/v0/postings/remedyproductstudio'),
('Accesssoftek', 'LEVER', 'accesssoftek', 'https://api.lever.co/v0/postings/accesssoftek'),
('Cyngn', 'LEVER', 'cyngn', 'https://api.lever.co/v0/postings/cyngn'),
('Craft-talent', 'LEVER', 'craft-talent', 'https://api.lever.co/v0/postings/craft-talent'),
('Carusoaffiliated', 'LEVER', 'carusoaffiliated', 'https://api.lever.co/v0/postings/carusoaffiliated'),
('Quadlock', 'LEVER', 'quadlock', 'https://api.lever.co/v0/postings/quadlock'),
('Csit', 'LEVER', 'csit', 'https://api.lever.co/v0/postings/csit'),
('Thoughtfulgpt', 'LEVER', 'thoughtfulgpt', 'https://api.lever.co/v0/postings/thoughtfulgpt'),
('Spmb', 'LEVER', 'spmb', 'https://api.lever.co/v0/postings/spmb'),
('Siteground', 'LEVER', 'siteground', 'https://api.lever.co/v0/postings/siteground'),
('Beyondcloudconsulting', 'LEVER', 'beyondcloudconsulting', 'https://api.lever.co/v0/postings/beyondcloudconsulting'),
('Algorex', 'LEVER', 'algorex', 'https://api.lever.co/v0/postings/algorex'),
('Tevora', 'LEVER', 'tevora', 'https://api.lever.co/v0/postings/tevora'),
('Happy-sleep', 'LEVER', 'happy-sleep', 'https://api.lever.co/v0/postings/happy-sleep'),
('Pphp', 'LEVER', 'pphp', 'https://api.lever.co/v0/postings/pphp'),
('Aisafety', 'LEVER', 'aisafety', 'https://api.lever.co/v0/postings/aisafety'),
('Applydigital', 'LEVER', 'applydigital', 'https://api.lever.co/v0/postings/applydigital')
ON CONFLICT (board_token) DO UPDATE 
SET name = EXCLUDED.name, ats_type = EXCLUDED.ats_type;