DROP TRIGGER IF EXISTS trg_jobs_search_vector_update ON jobs;
DROP FUNCTION IF EXISTS update_job_search_vector();
DROP PROCEDURE IF EXISTS expire_stale_jobs(UUID);
DROP TABLE IF EXISTS jobs CASCADE;
DROP TABLE IF EXISTS companies CASCADE;
DROP TYPE IF EXISTS job_status CASCADE;

-- Enable required extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Define custom ENUM for job lifecycle management
CREATE TYPE job_status AS ENUM ('ACTIVE', 'STALE', 'EXPIRED', 'ARCHIVED');

-- 1. Companies Table
CREATE TABLE companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL UNIQUE,
    ats_type VARCHAR(50) NOT NULL,            
    board_token VARCHAR(255) NOT NULL,        
    website_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Jobs Table
CREATE TABLE jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    company_name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    
    -- Role & Compensation
    experience_level VARCHAR(50),              -- e.g., 'Junior', 'Mid', 'Senior', 'Lead'
    employment_type VARCHAR(50),               -- e.g., 'Full-time', 'Contract', 'Internship'
    salary_min INTEGER,                        -- e.g., 90000
    salary_max INTEGER,                        -- e.g., 130000
    salary_currency VARCHAR(10) DEFAULT 'USD', -- e.g., 'USD', 'EUR', 'AED'
    
    location VARCHAR(255),
    department VARCHAR(255),
    description_text TEXT,
    apply_url TEXT NOT NULL,
    ats_job_id VARCHAR(100),                  
    
    -- Lifecycle State
    status job_status DEFAULT 'ACTIVE',
    
    -- Timestamps
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    
    -- PostgreSQL Full-Text Search Vector
    search_vector tsvector
);

-- 3. Indexes for Sub-Millisecond Search Performance
CREATE INDEX idx_jobs_search_vector ON jobs USING GIN (search_vector);
-- UPDATED: Now uses created_at instead of posted_at
CREATE INDEX idx_jobs_active_created ON jobs(status, created_at DESC);
CREATE INDEX idx_jobs_company_id ON jobs(company_id);

-- 🚀 Partial index heavily optimized for the expiration sweep
CREATE INDEX idx_jobs_sweep_optimizer ON jobs(company_id, last_seen_at) WHERE status = 'ACTIVE';

-- 4. Automated Search Vector Trigger
CREATE OR REPLACE FUNCTION update_job_search_vector() RETURNS trigger AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.experience_level, '')), 'A') || 
        setweight(to_tsvector('english', coalesce(NEW.department, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.location, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.description_text, '')), 'C');
    RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_jobs_search_vector_update
BEFORE INSERT OR UPDATE ON jobs
FOR EACH ROW EXECUTE FUNCTION update_job_search_vector();

-- 5. 🚀 The Sweeper Procedure
CREATE OR REPLACE PROCEDURE expire_stale_jobs(target_company_id UUID)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE jobs 
    SET status = 'EXPIRED'
    -- REMOVED closed_at update
    WHERE company_id = target_company_id 
      AND status = 'ACTIVE' 
      -- Expires anything not updated in the last 24 hours
      AND last_seen_at < (CURRENT_TIMESTAMP - INTERVAL '24 hours');
END;
$$;

SELECT current_database();

-- Clean insert for Middle East Talentera Portals
INSERT INTO companies (name, ats_type, board_token, website_url) VALUES 
('Mirror', 'LEVER', 'mirror', 'https://api.lever.co/v0/postings/mirror'),
('Spectrum', 'LEVER', 'spectrum', 'https://api.lever.co/v0/postings/spectrum'),
('Isee', 'LEVER', 'isee', 'https://api.lever.co/v0/postings/isee'),
('Grand', 'LEVER', 'grand', 'https://api.lever.co/v0/postings/grand'),
('Ashoka', 'LEVER', 'ashoka', 'https://api.lever.co/v0/postings/ashoka'),
('Aero', 'LEVER', 'aero', 'https://api.lever.co/v0/postings/aero'),
('Vana', 'LEVER', 'vana', 'https://api.lever.co/v0/postings/vana'),
('Cic', 'LEVER', 'cic', 'https://api.lever.co/v0/postings/cic'),
('Falcon', 'LEVER', 'falcon', 'https://api.lever.co/v0/postings/falcon'),
('Tonic', 'LEVER', 'tonic', 'https://api.lever.co/v0/postings/tonic'),
('Form', 'LEVER', 'form', 'https://api.lever.co/v0/postings/form'),
('Aleph', 'LEVER', 'aleph', 'https://api.lever.co/v0/postings/aleph'),
('Better', 'LEVER', 'better', 'https://api.lever.co/v0/postings/better'),
('Ion', 'LEVER', 'ion', 'https://api.lever.co/v0/postings/ion'),
('Incorta', 'LEVER', 'incorta', 'https://api.lever.co/v0/postings/incorta'),
('Florence', 'LEVER', 'florence', 'https://api.lever.co/v0/postings/florence'),
('Sure', 'LEVER', 'sure', 'https://api.lever.co/v0/postings/sure'),
('Accurate', 'LEVER', 'accurate', 'https://api.lever.co/v0/postings/accurate'),
('Tala', 'LEVER', 'tala', 'https://api.lever.co/v0/postings/tala'),
('Sila', 'LEVER', 'sila', 'https://api.lever.co/v0/postings/sila'),
('Career', 'LEVER', 'career', 'https://api.lever.co/v0/postings/career'),
('Sar', 'LEVER', 'sar', 'https://api.lever.co/v0/postings/sar'),
('Life', 'LEVER', 'life', 'https://api.lever.co/v0/postings/life'),
('Mazars', 'LEVER', 'mazars', 'https://api.lever.co/v0/postings/mazars'),
('Horizon', 'LEVER', 'horizon', 'https://api.lever.co/v0/postings/horizon'),
('Maya', 'LEVER', 'maya', 'https://api.lever.co/v0/postings/maya'),
('Source', 'LEVER', 'source', 'https://api.lever.co/v0/postings/source'),
('Nextech', 'LEVER', 'nextech', 'https://api.lever.co/v0/postings/nextech'),
('Greenlight', 'LEVER', 'greenlight', 'https://api.lever.co/v0/postings/greenlight'),
('Blue', 'LEVER', 'blue', 'https://api.lever.co/v0/postings/blue'),
('Raya', 'LEVER', 'raya', 'https://api.lever.co/v0/postings/raya'),
('Erg', 'LEVER', 'erg', 'https://api.lever.co/v0/postings/erg'),
('Hotstar', 'LEVER', 'hotstar', 'https://api.lever.co/v0/postings/hotstar'),
('Coins', 'LEVER', 'coins', 'https://api.lever.co/v0/postings/coins'),
('Retro', 'LEVER', 'retro', 'https://api.lever.co/v0/postings/retro'),
('Aldar', 'LEVER', 'aldar', 'https://api.lever.co/v0/postings/aldar'),
('Advocate', 'LEVER', 'advocate', 'https://api.lever.co/v0/postings/advocate'),
('Pattern', 'LEVER', 'pattern', 'https://api.lever.co/v0/postings/pattern'),
('Fantasy', 'LEVER', 'fantasy', 'https://api.lever.co/v0/postings/fantasy'),
('Rise', 'LEVER', 'rise', 'https://api.lever.co/v0/postings/rise'),
('Gamma', 'LEVER', 'gamma', 'https://api.lever.co/v0/postings/gamma'),
('Rai', 'LEVER', 'rai', 'https://api.lever.co/v0/postings/rai'),
('KPMG', 'LEVER', 'kpmg', 'https://api.lever.co/v0/postings/kpmg'),
('Reliable', 'LEVER', 'reliable', 'https://api.lever.co/v0/postings/reliable'),
('Trio', 'LEVER', 'trio', 'https://api.lever.co/v0/postings/trio'),
('Fortress', 'LEVER', 'fortress', 'https://api.lever.co/v0/postings/fortress'),
('Powerex', 'LEVER', 'powerex', 'https://api.lever.co/v0/postings/powerex'),
('Bigblue', 'LEVER', 'bigblue', 'https://api.lever.co/v0/postings/bigblue'),
('Angel', 'LEVER', 'angel', 'https://api.lever.co/v0/postings/angel'),
('Neon', 'LEVER', 'neon', 'https://api.lever.co/v0/postings/neon'),
('Avante', 'LEVER', 'avante', 'https://api.lever.co/v0/postings/avante'),
('Abt', 'LEVER', 'abt', 'https://api.lever.co/v0/postings/abt'),
('Gate', 'LEVER', 'gate', 'https://api.lever.co/v0/postings/gate'),
('Moo', 'LEVER', 'moo', 'https://api.lever.co/v0/postings/moo'),
('Capital', 'LEVER', 'capital', 'https://api.lever.co/v0/postings/capital'),
('Tag', 'LEVER', 'tag', 'https://api.lever.co/v0/postings/tag'),
('Lever', 'LEVER', 'lever', 'https://api.lever.co/v0/postings/lever'),
('Beta', 'LEVER', 'beta', 'https://api.lever.co/v0/postings/beta'),
('Sep', 'LEVER', 'sep', 'https://api.lever.co/v0/postings/sep'),
('Assurance', 'LEVER', 'assurance', 'https://api.lever.co/v0/postings/assurance'),
('Harmony', 'LEVER', 'harmony', 'https://api.lever.co/v0/postings/harmony'),
('Dutch', 'LEVER', 'dutch', 'https://api.lever.co/v0/postings/dutch'),
('Text', 'LEVER', 'text', 'https://api.lever.co/v0/postings/text'),
('Lemon', 'LEVER', 'lemon', 'https://api.lever.co/v0/postings/lemon'),
('Safe', 'LEVER', 'safe', 'https://api.lever.co/v0/postings/safe'),
('Terminus', 'LEVER', 'terminus', 'https://api.lever.co/v0/postings/terminus'),
('Jmi', 'LEVER', 'jmi', 'https://api.lever.co/v0/postings/jmi'),
('Crossfit', 'LEVER', 'crossfit', 'https://api.lever.co/v0/postings/crossfit'),
('Aquarium', 'LEVER', 'aquarium', 'https://api.lever.co/v0/postings/aquarium'),
('Charcuterie', 'LEVER', 'charcuterie', 'https://api.lever.co/v0/postings/charcuterie'),
('Adora', 'LEVER', 'adora', 'https://api.lever.co/v0/postings/adora'),
('Mega', 'LEVER', 'mega', 'https://api.lever.co/v0/postings/mega'),
('Signal', 'LEVER', 'signal', 'https://api.lever.co/v0/postings/signal'),
('Espace', 'LEVER', 'espace', 'https://api.lever.co/v0/postings/espace'),
('Relay', 'LEVER', 'relay', 'https://api.lever.co/v0/postings/relay'),
('Sfeir', 'LEVER', 'sfeir', 'https://api.lever.co/v0/postings/sfeir'),
('Deputy', 'LEVER', 'deputy', 'https://api.lever.co/v0/postings/deputy'),
('Mawsim', 'LEVER', 'mawsim', 'https://api.lever.co/v0/postings/mawsim'),
('Ans', 'LEVER', 'ans', 'https://api.lever.co/v0/postings/ans'),
('Brilliant', 'LEVER', 'brilliant', 'https://api.lever.co/v0/postings/brilliant'),
('Computercare', 'LEVER', 'computercare', 'https://api.lever.co/v0/postings/computercare'),
('Abdullah Abdulghani & Bros (AAB)', 'TALENTERA', 'aab', 'https://aab.talentera.com'),
('Telecommunications Regulatory Authority', 'TALENTERA', 'tra', 'https://tra.talentera.com'),
('Royal Jordanian', 'TALENTERA', 'royaljordanian', 'https://royaljordanian.talentera.com'),
('Mobica', 'TALENTERA', 'mobica', 'https://mobica.talentera.com'),
('Masar', 'TALENTERA', 'masar', 'https://masar.talentera.com'),
('Tamimi Markets', 'TALENTERA', 'tamimi', 'https://tamimi.talentera.com'),
('Mobily', 'TALENTERA', 'mobily', 'https://mobily.talentera.com'),
('Orange Bed & Bath', 'TALENTERA', 'orangebedbath', 'https://orangebedbath.talentera.com'),
('Magrabi', 'TALENTERA', 'magrabi', 'https://magrabi.talentera.com'),
('Rawabi Holding', 'TALENTERA', 'rawabi', 'https://rawabi.talentera.com'),
('Itqan', 'TALENTERA', 'itqan', 'https://itqan.talentera.com'),
('Council of Health Insurance (CHI)', 'TALENTERA', 'chi', 'https://chi.talentera.com'),
('Radwa Food Products', 'TALENTERA', 'radwa', 'https://radwa.talentera.com'),
('Talentera Careers', 'TALENTERA', 'careers', 'https://careers.talentera.com'),
('Integral', 'TALENTERA', 'integral', 'https://integral.talentera.com'),
('National Center for Environmental Compliance (NCEC)', 'TALENTERA', 'ncec', 'https://ncec.talentera.com'),
('Panda Retail Company', 'TALENTERA', 'panda', 'https://panda.talentera.com'),
('BEAM', 'TALENTERA', 'beam', 'https://beam.talentera.com'),
('Care National Hospital', 'TALENTERA', 'care', 'https://care.talentera.com'),
('Badruddin', 'TALENTERA', 'badruddin', 'https://badruddin.talentera.com'),
('Saudi Investment Bank (SAIB)', 'TALENTERA', 'saib', 'https://saib.talentera.com'),
('General Organization for Social Insurance (GOSI)', 'TALENTERA', 'gosi', 'https://gosi.talentera.com'),
('Al-Dawaa Pharmacies', 'TALENTERA', 'al-dawaa', 'https://al-dawaa.talentera.com'),
('Save the Children', 'TALENTERA', 'savethechildren', 'https://savethechildren.talentera.com'),
('Taiba Investments', 'TALENTERA', 'taiba', 'https://taiba.talentera.com'),
('Concrete', 'TALENTERA', 'concrete', 'https://concrete.talentera.com'),
('Maliks', 'TALENTERA', 'maliks', 'https://maliks.talentera.com'),
('Ejada', 'TALENTERA', 'ejada', 'https://ejada.talentera.com'),
('Talentera Demo', 'TALENTERA', 'demo', 'https://demo.talentera.com'),
('Saudi Bar Association (SBA)', 'TALENTERA', 'sba', 'https://sba.talentera.com'),
('Choithrams', 'TALENTERA', 'choithrams', 'https://choithrams.talentera.com'),
('Alfardan Group', 'TALENTERA', 'alfardan', 'https://alfardan.talentera.com'),
('Gulf International Bank (GIB)', 'TALENTERA', 'gib', 'https://gib.talentera.com'),
('MSD', 'TALENTERA', 'msd', 'https://msd.talentera.com'),
('SAL Saudi Logistics Services', 'TALENTERA', 'sal', 'https://sal.talentera.com'),
('Saudi Petroleum Services Polytechnic (SPSP)', 'TALENTERA', 'spsp', 'https://spsp.talentera.com'),
('Batelco', 'TALENTERA', 'batelco', 'https://batelco.talentera.com'),
('National Water Company (NWC)', 'TALENTERA', 'nwc', 'https://nwc.talentera.com'),
('Capital Market Authority (CMA)', 'TALENTERA', 'cma', 'https://cma.talentera.com'),
('MODON', 'TALENTERA', 'modon', 'https://modon.talentera.com'),
('Al Rashed', 'TALENTERA', 'alrashed', 'https://alrashed.talentera.com')
('Gps', 'GREENHOUSE', 'gps', 'https://boards.greenhouse.io/gps'),
('London', 'GREENHOUSE', 'london', 'https://boards.greenhouse.io/london'),
('Orca', 'GREENHOUSE', 'orca', 'https://boards.greenhouse.io/orca'),
('Spotlight', 'GREENHOUSE', 'spotlight', 'https://boards.greenhouse.io/spotlight'),
('Kayak', 'GREENHOUSE', 'kayak', 'https://boards.greenhouse.io/kayak'),
('National', 'GREENHOUSE', 'national', 'https://boards.greenhouse.io/national'),
('Alx', 'GREENHOUSE', 'alx', 'https://boards.greenhouse.io/alx'),
('Gemini', 'GREENHOUSE', 'gemini', 'https://boards.greenhouse.io/gemini'),
('Concentric', 'GREENHOUSE', 'concentric', 'https://boards.greenhouse.io/concentric'),
('Magnolia', 'GREENHOUSE', 'magnolia', 'https://boards.greenhouse.io/magnolia'),
('Stage', 'GREENHOUSE', 'stage', 'https://boards.greenhouse.io/stage'),
('Galileo', 'GREENHOUSE', 'galileo', 'https://boards.greenhouse.io/galileo'),
('Raven', 'GREENHOUSE', 'raven', 'https://boards.greenhouse.io/raven'),
('Super', 'GREENHOUSE', 'super', 'https://boards.greenhouse.io/super'),
('Digit', 'GREENHOUSE', 'digit', 'https://boards.greenhouse.io/digit'),
('Apollo', 'GREENHOUSE', 'apollo', 'https://boards.greenhouse.io/apollo'),
('Tulip', 'GREENHOUSE', 'tulip', 'https://boards.greenhouse.io/tulip'),
('Pvi', 'GREENHOUSE', 'pvi', 'https://boards.greenhouse.io/pvi'),
('Denver', 'GREENHOUSE', 'denver', 'https://boards.greenhouse.io/denver'),
('Chicago', 'GREENHOUSE', 'chicago', 'https://boards.greenhouse.io/chicago'),
('Tide', 'GREENHOUSE', 'tide', 'https://boards.greenhouse.io/tide'),
('Flourish', 'GREENHOUSE', 'flourish', 'https://boards.greenhouse.io/flourish'),
('Bob', 'GREENHOUSE', 'bob', 'https://boards.greenhouse.io/bob'),
('Brothers', 'GREENHOUSE', 'brothers', 'https://boards.greenhouse.io/brothers'),
('Taa', 'GREENHOUSE', 'taa', 'https://boards.greenhouse.io/taa'),
('Regent', 'GREENHOUSE', 'regent', 'https://boards.greenhouse.io/regent'),
('Nex', 'GREENHOUSE', 'nex', 'https://boards.greenhouse.io/nex'),
('Abc', 'GREENHOUSE', 'abc', 'https://boards.greenhouse.io/abc'),
('Flamingo', 'GREENHOUSE', 'flamingo', 'https://boards.greenhouse.io/flamingo'),
('Glow', 'GREENHOUSE', 'glow', 'https://boards.greenhouse.io/glow'),
('Reflex', 'GREENHOUSE', 'reflex', 'https://boards.greenhouse.io/reflex'),
('Korea', 'GREENHOUSE', 'korea', 'https://boards.greenhouse.io/korea'),
('Its', 'GREENHOUSE', 'its', 'https://boards.greenhouse.io/its'),
('Coast', 'GREENHOUSE', 'coast', 'https://boards.greenhouse.io/coast'),
('Indigo', 'GREENHOUSE', 'indigo', 'https://boards.greenhouse.io/indigo'),
('Metropolis', 'GREENHOUSE', 'metropolis', 'https://boards.greenhouse.io/metropolis'),
('Oldcity', 'GREENHOUSE', 'oldcity', 'https://boards.greenhouse.io/oldcity'),
('Paradigm', 'GREENHOUSE', 'paradigm', 'https://boards.greenhouse.io/paradigm'),
('Alabaster', 'GREENHOUSE', 'alabaster', 'https://boards.greenhouse.io/alabaster'),
('Octave', 'GREENHOUSE', 'octave', 'https://boards.greenhouse.io/octave'),
('Reliant', 'GREENHOUSE', 'reliant', 'https://boards.greenhouse.io/reliant'),
('Headquarter', 'GREENHOUSE', 'headquarter', 'https://boards.greenhouse.io/headquarter'),
('Lightworks', 'GREENHOUSE', 'lightworks', 'https://boards.greenhouse.io/lightworks'),
('Bloom', 'GREENHOUSE', 'bloom', 'https://boards.greenhouse.io/bloom'),
('Rak', 'GREENHOUSE', 'rak', 'https://boards.greenhouse.io/rak'),
('Shield', 'GREENHOUSE', 'shield', 'https://boards.greenhouse.io/shield'),
('Upkeep', 'GREENHOUSE', 'upkeep', 'https://boards.greenhouse.io/upkeep'),
('Truemedia', 'GREENHOUSE', 'truemedia', 'https://boards.greenhouse.io/truemedia'),
('Soci', 'GREENHOUSE', 'soci', 'https://boards.greenhouse.io/soci'),
('Dna', 'GREENHOUSE', 'dna', 'https://boards.greenhouse.io/dna'),
('Administrative', 'GREENHOUSE', 'administrative', 'https://boards.greenhouse.io/administrative'),
('Athletics', 'GREENHOUSE', 'athletics', 'https://boards.greenhouse.io/athletics'),
('Sei', 'GREENHOUSE', 'sei', 'https://boards.greenhouse.io/sei'),
('Metro', 'GREENHOUSE', 'metro', 'https://boards.greenhouse.io/metro'),
('Athena', 'GREENHOUSE', 'athena', 'https://boards.greenhouse.io/athena'),
('Support', 'GREENHOUSE', 'support', 'https://boards.greenhouse.io/support'),
('Hunterdouglas', 'GREENHOUSE', 'hunterdouglas', 'https://boards.greenhouse.io/hunterdouglas'),
('Zoro', 'GREENHOUSE', 'zoro', 'https://boards.greenhouse.io/zoro'),
('Carbon', 'GREENHOUSE', 'carbon', 'https://boards.greenhouse.io/carbon'),
('Greenline', 'GREENHOUSE', 'greenline', 'https://boards.greenhouse.io/greenline'),
('Pioneer', 'GREENHOUSE', 'pioneer', 'https://boards.greenhouse.io/pioneer'),
('Yes', 'GREENHOUSE', 'yes', 'https://boards.greenhouse.io/yes'),
('Avani', 'GREENHOUSE', 'avani', 'https://boards.greenhouse.io/avani'),
('Help', 'GREENHOUSE', 'help', 'https://boards.greenhouse.io/help'),
('Eclipse', 'GREENHOUSE', 'eclipse', 'https://boards.greenhouse.io/eclipse'),
('Jaguar', 'GREENHOUSE', 'jaguar', 'https://boards.greenhouse.io/jaguar'),
('Dino', 'GREENHOUSE', 'dino', 'https://boards.greenhouse.io/dino'),
('Koko', 'GREENHOUSE', 'koko', 'https://boards.greenhouse.io/koko'),
('Rmr', 'GREENHOUSE', 'rmr', 'https://boards.greenhouse.io/rmr'),
('New', 'GREENHOUSE', 'new', 'https://boards.greenhouse.io/new'),
('Sao', 'GREENHOUSE', 'sao', 'https://boards.greenhouse.io/sao'),
('Tomorrow', 'GREENHOUSE', 'tomorrow', 'https://boards.greenhouse.io/tomorrow'),
('Stone', 'GREENHOUSE', 'stone', 'https://boards.greenhouse.io/stone'),
('Seed', 'GREENHOUSE', 'seed', 'https://boards.greenhouse.io/seed'),
('Iris', 'GREENHOUSE', 'iris', 'https://boards.greenhouse.io/iris'),
('Comet', 'GREENHOUSE', 'comet', 'https://boards.greenhouse.io/comet'),
('Investment', 'GREENHOUSE', 'investment', 'https://boards.greenhouse.io/investment'),
('Ghost', 'GREENHOUSE', 'ghost', 'https://boards.greenhouse.io/ghost'),
('Casa', 'GREENHOUSE', 'casa', 'https://boards.greenhouse.io/casa'),
('Nursing', 'GREENHOUSE', 'nursing', 'https://boards.greenhouse.io/nursing'),
('Shaker', 'GREENHOUSE', 'shaker', 'https://boards.greenhouse.io/shaker'),
('Encore', 'GREENHOUSE', 'encore', 'https://boards.greenhouse.io/encore'),
('Range', 'GREENHOUSE', 'range', 'https://boards.greenhouse.io/range'),
('Ref', 'GREENHOUSE', 'ref', 'https://boards.greenhouse.io/ref'),
('Moneymart', 'GREENHOUSE', 'moneymart', 'https://boards.greenhouse.io/moneymart'),
('Excel', 'GREENHOUSE', 'excel', 'https://boards.greenhouse.io/excel'),
('Optimal', 'GREENHOUSE', 'optimal', 'https://boards.greenhouse.io/optimal'),
('Gateway', 'GREENHOUSE', 'gateway', 'https://boards.greenhouse.io/gateway'),
('Reach', 'GREENHOUSE', 'reach', 'https://boards.greenhouse.io/reach'),
('Slice', 'GREENHOUSE', 'slice', 'https://boards.greenhouse.io/slice'),
('Forward', 'GREENHOUSE', 'forward', 'https://boards.greenhouse.io/forward'),
('Fox', 'GREENHOUSE', 'fox', 'https://boards.greenhouse.io/fox'),
('Isa', 'GREENHOUSE', 'isa', 'https://boards.greenhouse.io/isa'),
('Murad', 'GREENHOUSE', 'murad', 'https://boards.greenhouse.io/murad'),
('Sunrise', 'GREENHOUSE', 'sunrise', 'https://boards.greenhouse.io/sunrise'),
('Sada', 'GREENHOUSE', 'sada', 'https://boards.greenhouse.io/sada'),
('Pine', 'GREENHOUSE', 'pine', 'https://boards.greenhouse.io/pine'),
('Charles', 'GREENHOUSE', 'charles', 'https://boards.greenhouse.io/charles'),
('Proton', 'GREENHOUSE', 'proton', 'https://boards.greenhouse.io/proton'),
('Clever', 'GREENHOUSE', 'clever', 'https://boards.greenhouse.io/clever'),
('Sts', 'GREENHOUSE', 'sts', 'https://boards.greenhouse.io/sts'),
('Private', 'GREENHOUSE', 'private', 'https://boards.greenhouse.io/private'),
('Netherlands', 'GREENHOUSE', 'netherlands', 'https://boards.greenhouse.io/netherlands'),
('Hala', 'GREENHOUSE', 'hala', 'https://boards.greenhouse.io/hala'),
('Amca', 'GREENHOUSE', 'amca', 'https://boards.greenhouse.io/amca'),
('Truckstop', 'GREENHOUSE', 'truckstop', 'https://boards.greenhouse.io/truckstop'),
('Moon', 'GREENHOUSE', 'moon', 'https://boards.greenhouse.io/moon'),
('Boulevard', 'GREENHOUSE', 'boulevard', 'https://boards.greenhouse.io/boulevard'),
('Parkland', 'GREENHOUSE', 'parkland', 'https://boards.greenhouse.io/parkland'),
('Axiom', 'GREENHOUSE', 'axiom', 'https://boards.greenhouse.io/axiom'),
('Newhope', 'GREENHOUSE', 'newhope', 'https://boards.greenhouse.io/newhope'),
('Sonic', 'GREENHOUSE', 'sonic', 'https://boards.greenhouse.io/sonic'),
('Techno', 'GREENHOUSE', 'techno', 'https://boards.greenhouse.io/techno'),
('Genuine', 'GREENHOUSE', 'genuine', 'https://boards.greenhouse.io/genuine'),
('Careem', 'GREENHOUSE', 'careem', 'https://boards.greenhouse.io/careem'),
('Tribal', 'GREENHOUSE', 'tribal', 'https://boards.greenhouse.io/tribal'),
('Drc', 'GREENHOUSE', 'drc', 'https://boards.greenhouse.io/drc'),
('Homeland', 'GREENHOUSE', 'homeland', 'https://boards.greenhouse.io/homeland'),
('Vibes', 'GREENHOUSE', 'vibes', 'https://boards.greenhouse.io/vibes'),
('Mesh', 'GREENHOUSE', 'mesh', 'https://boards.greenhouse.io/mesh'),
('Chata', 'GREENHOUSE', 'chata', 'https://boards.greenhouse.io/chata'),
('Cabin', 'GREENHOUSE', 'cabin', 'https://boards.greenhouse.io/cabin'),
('Kansas', 'GREENHOUSE', 'kansas', 'https://boards.greenhouse.io/kansas'),
('Polaris', 'GREENHOUSE', 'polaris', 'https://boards.greenhouse.io/polaris'),
('Peak', 'GREENHOUSE', 'peak', 'https://boards.greenhouse.io/peak'),
('Magic', 'GREENHOUSE', 'magic', 'https://boards.greenhouse.io/magic'),
('Oscar', 'GREENHOUSE', 'oscar', 'https://boards.greenhouse.io/oscar'),
('Mobi', 'GREENHOUSE', 'mobi', 'https://boards.greenhouse.io/mobi'),
('Broadway', 'GREENHOUSE', 'broadway', 'https://boards.greenhouse.io/broadway'),
('Efs', 'GREENHOUSE', 'efs', 'https://boards.greenhouse.io/efs'),
('Sterling', 'GREENHOUSE', 'sterling', 'https://boards.greenhouse.io/sterling'),
('Integrated', 'GREENHOUSE', 'integrated', 'https://boards.greenhouse.io/integrated'),
('Isam', 'GREENHOUSE', 'isam', 'https://boards.greenhouse.io/isam'),
('Link', 'GREENHOUSE', 'link', 'https://boards.greenhouse.io/link'),
('Evergreen', 'GREENHOUSE', 'evergreen', 'https://boards.greenhouse.io/evergreen'),
('Ideo', 'GREENHOUSE', 'ideo', 'https://boards.greenhouse.io/ideo'),
('Candles', 'GREENHOUSE', 'candles', 'https://boards.greenhouse.io/candles'),
('Flex', 'GREENHOUSE', 'flex', 'https://boards.greenhouse.io/flex'),
('Gusto', 'GREENHOUSE', 'gusto', 'https://boards.greenhouse.io/gusto'),
('Maxwell', 'GREENHOUSE', 'maxwell', 'https://boards.greenhouse.io/maxwell'),
('Make', 'GREENHOUSE', 'make', 'https://boards.greenhouse.io/make'),
('Industrial', 'GREENHOUSE', 'industrial', 'https://boards.greenhouse.io/industrial'),
('Mit', 'GREENHOUSE', 'mit', 'https://boards.greenhouse.io/mit'),
('Wundermanthompson', 'GREENHOUSE', 'wundermanthompson', 'https://boards.greenhouse.io/wundermanthompson'),
('Talent', 'GREENHOUSE', 'talent', 'https://boards.greenhouse.io/talent'),
('Independent', 'GREENHOUSE', 'independent', 'https://boards.greenhouse.io/independent'),
('Makina', 'GREENHOUSE', 'makina', 'https://boards.greenhouse.io/makina'),
('David', 'GREENHOUSE', 'david', 'https://boards.greenhouse.io/david'),
('Tcs', 'GREENHOUSE', 'tcs', 'https://boards.greenhouse.io/tcs'),
('Firstday', 'GREENHOUSE', 'firstday', 'https://boards.greenhouse.io/firstday'),
('Calm', 'GREENHOUSE', 'calm', 'https://boards.greenhouse.io/calm'),
('Sas', 'GREENHOUSE', 'sas', 'https://boards.greenhouse.io/sas'),
('Victory', 'GREENHOUSE', 'victory', 'https://boards.greenhouse.io/victory'),
('Emi', 'GREENHOUSE', 'emi', 'https://boards.greenhouse.io/emi'),
('Nexus', 'GREENHOUSE', 'nexus', 'https://boards.greenhouse.io/nexus'),
('Regie', 'GREENHOUSE', 'regie', 'https://boards.greenhouse.io/regie'),
('Solutions', 'GREENHOUSE', 'solutions', 'https://boards.greenhouse.io/solutions'),
('B12', 'GREENHOUSE', 'b12', 'https://boards.greenhouse.io/b12'),
('Dallas', 'GREENHOUSE', 'dallas', 'https://boards.greenhouse.io/dallas'),
('Sabino', 'GREENHOUSE', 'sabino', 'https://boards.greenhouse.io/sabino'),
('Kit', 'GREENHOUSE', 'kit', 'https://boards.greenhouse.io/kit'),
('Japan', 'GREENHOUSE', 'japan', 'https://boards.greenhouse.io/japan'),
('Antigua', 'GREENHOUSE', 'antigua', 'https://boards.greenhouse.io/antigua'),
('Imc', 'GREENHOUSE', 'imc', 'https://boards.greenhouse.io/imc'),
('Testing', 'GREENHOUSE', 'testing', 'https://boards.greenhouse.io/testing'),
('Elitetechnology', 'GREENHOUSE', 'elitetechnology', 'https://boards.greenhouse.io/elitetechnology'),
('General', 'GREENHOUSE', 'general', 'https://boards.greenhouse.io/general'),
('Gravity', 'GREENHOUSE', 'gravity', 'https://boards.greenhouse.io/gravity'),
('Tss', 'GREENHOUSE', 'tss', 'https://boards.greenhouse.io/tss'),
('Sunset', 'GREENHOUSE', 'sunset', 'https://boards.greenhouse.io/sunset'),
('Jay', 'GREENHOUSE', 'jay', 'https://boards.greenhouse.io/jay'),
('Scanner', 'GREENHOUSE', 'scanner', 'https://boards.greenhouse.io/scanner'),
('Workshop', 'GREENHOUSE', 'workshop', 'https://boards.greenhouse.io/workshop'),
('Explore', 'GREENHOUSE', 'explore', 'https://boards.greenhouse.io/explore'),
('Flix', 'GREENHOUSE', 'flix', 'https://boards.greenhouse.io/flix'),
('Space', 'GREENHOUSE', 'space', 'https://boards.greenhouse.io/space'),
('Universal', 'GREENHOUSE', 'universal', 'https://boards.greenhouse.io/universal'),
('Journey', 'GREENHOUSE', 'journey', 'https://boards.greenhouse.io/journey'),
('Tec', 'GREENHOUSE', 'tec', 'https://boards.greenhouse.io/tec'),
('Galaxy', 'GREENHOUSE', 'galaxy', 'https://boards.greenhouse.io/galaxy'),
('Branch', 'GREENHOUSE', 'branch', 'https://boards.greenhouse.io/branch'),
('Echo', 'GREENHOUSE', 'echo', 'https://boards.greenhouse.io/echo'),
('Location', 'GREENHOUSE', 'location', 'https://boards.greenhouse.io/location'),
('Shadow', 'GREENHOUSE', 'shadow', 'https://boards.greenhouse.io/shadow'),
('Edison', 'GREENHOUSE', 'edison', 'https://boards.greenhouse.io/edison'),
('Tiptop', 'GREENHOUSE', 'tiptop', 'https://boards.greenhouse.io/tiptop'),
('Philippines', 'GREENHOUSE', 'philippines', 'https://boards.greenhouse.io/philippines'),
('Name', 'GREENHOUSE', 'name', 'https://boards.greenhouse.io/name'),
('Mas', 'GREENHOUSE', 'mas', 'https://boards.greenhouse.io/mas'),
('Res', 'GREENHOUSE', 'res', 'https://boards.greenhouse.io/res'),
('Tpm', 'GREENHOUSE', 'tpm', 'https://boards.greenhouse.io/tpm'),
('Lighthouse', 'GREENHOUSE', 'lighthouse', 'https://boards.greenhouse.io/lighthouse'),
('Champion', 'GREENHOUSE', 'champion', 'https://boards.greenhouse.io/champion'),
('Ensemble', 'GREENHOUSE', 'ensemble', 'https://boards.greenhouse.io/ensemble'),
('Bold', 'GREENHOUSE', 'bold', 'https://boards.greenhouse.io/bold'),
('Bridgeway', 'GREENHOUSE', 'bridgeway', 'https://boards.greenhouse.io/bridgeway'),
('Clear', 'GREENHOUSE', 'clear', 'https://boards.greenhouse.io/clear'),
('Any', 'GREENHOUSE', 'any', 'https://boards.greenhouse.io/any'),
('Newton', 'GREENHOUSE', 'newton', 'https://boards.greenhouse.io/newton'),
('Cts', 'GREENHOUSE', 'cts', 'https://boards.greenhouse.io/cts'),
('Joya', 'GREENHOUSE', 'joya', 'https://boards.greenhouse.io/joya'),
('Finance', 'GREENHOUSE', 'finance', 'https://boards.greenhouse.io/finance'),
('Axon', 'GREENHOUSE', 'axon', 'https://boards.greenhouse.io/axon'),
('Aziz', 'GREENHOUSE', 'aziz', 'https://boards.greenhouse.io/aziz'),
('Symphony', 'GREENHOUSE', 'symphony', 'https://boards.greenhouse.io/symphony'),
('Aura', 'GREENHOUSE', 'aura', 'https://boards.greenhouse.io/aura'),
('Coop', 'GREENHOUSE', 'coop', 'https://boards.greenhouse.io/coop'),
('Gmp', 'GREENHOUSE', 'gmp', 'https://boards.greenhouse.io/gmp'),
('Future', 'GREENHOUSE', 'future', 'https://boards.greenhouse.io/future'),
('Locals', 'GREENHOUSE', 'locals', 'https://boards.greenhouse.io/locals'),
('Orchestra', 'GREENHOUSE', 'orchestra', 'https://boards.greenhouse.io/orchestra'),
('Cycles', 'GREENHOUSE', 'cycles', 'https://boards.greenhouse.io/cycles'),
('Contracts', 'GREENHOUSE', 'contracts', 'https://boards.greenhouse.io/contracts'),
('Bees', 'GREENHOUSE', 'bees', 'https://boards.greenhouse.io/bees'),
('Shepherd', 'GREENHOUSE', 'shepherd', 'https://boards.greenhouse.io/shepherd'),
('Daylight', 'GREENHOUSE', 'daylight', 'https://boards.greenhouse.io/daylight'),
('Hologram', 'GREENHOUSE', 'hologram', 'https://boards.greenhouse.io/hologram'),
('Pharmacy', 'GREENHOUSE', 'pharmacy', 'https://boards.greenhouse.io/pharmacy'),
('Ultimate', 'GREENHOUSE', 'ultimate', 'https://boards.greenhouse.io/ultimate'),
('Vaya', 'GREENHOUSE', 'vaya', 'https://boards.greenhouse.io/vaya'),
('Engine', 'GREENHOUSE', 'engine', 'https://boards.greenhouse.io/engine'),
('Intercom', 'GREENHOUSE', 'intercom', 'https://boards.greenhouse.io/intercom'),
('Events', 'GREENHOUSE', 'events', 'https://boards.greenhouse.io/events'),
('Find', 'GREENHOUSE', 'find', 'https://boards.greenhouse.io/find'),
('Test', 'GREENHOUSE', 'test', 'https://boards.greenhouse.io/test'),
('Keen', 'GREENHOUSE', 'keen', 'https://boards.greenhouse.io/keen'),
('Public', 'GREENHOUSE', 'public', 'https://boards.greenhouse.io/public'),
('Highland', 'GREENHOUSE', 'highland', 'https://boards.greenhouse.io/highland'),
('Sra', 'GREENHOUSE', 'sra', 'https://boards.greenhouse.io/sra'),
('Forte', 'GREENHOUSE', 'forte', 'https://boards.greenhouse.io/forte'),
('Disney', 'GREENHOUSE', 'disney', 'https://boards.greenhouse.io/disney'),
('Lor', 'GREENHOUSE', 'lor', 'https://boards.greenhouse.io/lor'),
('Flash', 'GREENHOUSE', 'flash', 'https://boards.greenhouse.io/flash'),
('Berelaxspa', 'GREENHOUSE', 'berelaxspa', 'https://boards.greenhouse.io/berelaxspa'),
('Air', 'GREENHOUSE', 'air', 'https://boards.greenhouse.io/air'),
('Cannondale', 'GREENHOUSE', 'cannondale', 'https://boards.greenhouse.io/cannondale'),
('Silicon', 'GREENHOUSE', 'silicon', 'https://boards.greenhouse.io/silicon'),
('Fourstar', 'GREENHOUSE', 'fourstar', 'https://boards.greenhouse.io/fourstar'),
('Prisma', 'GREENHOUSE', 'prisma', 'https://boards.greenhouse.io/prisma'),
('International', 'GREENHOUSE', 'international', 'https://boards.greenhouse.io/international'),
('Beyond', 'GREENHOUSE', 'beyond', 'https://boards.greenhouse.io/beyond'),
('Cais', 'GREENHOUSE', 'cais', 'https://boards.greenhouse.io/cais'),
('Colorado', 'GREENHOUSE', 'colorado', 'https://boards.greenhouse.io/colorado'),
('Spain', 'GREENHOUSE', 'spain', 'https://boards.greenhouse.io/spain'),
('Zoo', 'GREENHOUSE', 'zoo', 'https://boards.greenhouse.io/zoo'),
('Genius', 'GREENHOUSE', 'genius', 'https://boards.greenhouse.io/genius'),
('Aha', 'GREENHOUSE', 'aha', 'https://boards.greenhouse.io/aha'),
('Village', 'GREENHOUSE', 'village', 'https://boards.greenhouse.io/village'),
('Nectar', 'GREENHOUSE', 'nectar', 'https://boards.greenhouse.io/nectar'),
('Lush', 'GREENHOUSE', 'lush', 'https://boards.greenhouse.io/lush'),
('Supreme', 'GREENHOUSE', 'supreme', 'https://boards.greenhouse.io/supreme'),
('Transform', 'GREENHOUSE', 'transform', 'https://boards.greenhouse.io/transform'),
('Alliance', 'GREENHOUSE', 'alliance', 'https://boards.greenhouse.io/alliance'),
('Festival', 'GREENHOUSE', 'festival', 'https://boards.greenhouse.io/festival'),
('Apex', 'GREENHOUSE', 'apex', 'https://boards.greenhouse.io/apex'),
('Kite', 'GREENHOUSE', 'kite', 'https://boards.greenhouse.io/kite'),
('Rga', 'GREENHOUSE', 'rga', 'https://boards.greenhouse.io/rga'),
('Icon', 'GREENHOUSE', 'icon', 'https://boards.greenhouse.io/icon'),
('Rab', 'GREENHOUSE', 'rab', 'https://boards.greenhouse.io/rab'),
('Esri', 'GREENHOUSE', 'esri', 'https://boards.greenhouse.io/esri'),
('Basic', 'GREENHOUSE', 'basic', 'https://boards.greenhouse.io/basic'),
('Place', 'GREENHOUSE', 'place', 'https://boards.greenhouse.io/place'),
('Allied', 'GREENHOUSE', 'allied', 'https://boards.greenhouse.io/allied'),
('Blend', 'GREENHOUSE', 'blend', 'https://boards.greenhouse.io/blend'),
('Selling', 'GREENHOUSE', 'selling', 'https://boards.greenhouse.io/selling'),
('Osmosis', 'GREENHOUSE', 'osmosis', 'https://boards.greenhouse.io/osmosis'),
('Goal', 'GREENHOUSE', 'goal', 'https://boards.greenhouse.io/goal'),
('Map', 'GREENHOUSE', 'map', 'https://boards.greenhouse.io/map'),
('Summer', 'GREENHOUSE', 'summer', 'https://boards.greenhouse.io/summer'),
('Alta', 'GREENHOUSE', 'alta', 'https://boards.greenhouse.io/alta'),
('Maro', 'GREENHOUSE', 'maro', 'https://boards.greenhouse.io/maro'),
('Fourseasons', 'GREENHOUSE', 'fourseasons', 'https://boards.greenhouse.io/fourseasons'),
('Elite', 'GREENHOUSE', 'elite', 'https://boards.greenhouse.io/elite'),
('Ampm', 'GREENHOUSE', 'ampm', 'https://boards.greenhouse.io/ampm'),
('Maestro', 'GREENHOUSE', 'maestro', 'https://boards.greenhouse.io/maestro'),
('Via', 'GREENHOUSE', 'via', 'https://boards.greenhouse.io/via'),
('Ohio', 'GREENHOUSE', 'ohio', 'https://boards.greenhouse.io/ohio'),
('A24', 'GREENHOUSE', 'a24', 'https://boards.greenhouse.io/a24'),
('Alu', 'GREENHOUSE', 'alu', 'https://boards.greenhouse.io/alu'),
('Technology', 'GREENHOUSE', 'technology', 'https://boards.greenhouse.io/technology'),
('Glance', 'GREENHOUSE', 'glance', 'https://boards.greenhouse.io/glance'),
('Tekla', 'GREENHOUSE', 'tekla', 'https://boards.greenhouse.io/tekla'),
('Neu', 'GREENHOUSE', 'neu', 'https://boards.greenhouse.io/neu'),
('System', 'GREENHOUSE', 'system', 'https://boards.greenhouse.io/system'),
('Insurance', 'GREENHOUSE', 'insurance', 'https://boards.greenhouse.io/insurance'),
('Education', 'GREENHOUSE', 'education', 'https://boards.greenhouse.io/education'),
('Harbor', 'GREENHOUSE', 'harbor', 'https://boards.greenhouse.io/harbor'),
('Moltonbrown', 'GREENHOUSE', 'moltonbrown', 'https://boards.greenhouse.io/moltonbrown'),
('Uplift', 'GREENHOUSE', 'uplift', 'https://boards.greenhouse.io/uplift'),
('Pia', 'GREENHOUSE', 'pia', 'https://boards.greenhouse.io/pia'),
('Network', 'GREENHOUSE', 'network', 'https://boards.greenhouse.io/network'),
('Grey', 'GREENHOUSE', 'grey', 'https://boards.greenhouse.io/grey'),
('Lasenza', 'GREENHOUSE', 'lasenza', 'https://boards.greenhouse.io/lasenza'),
('Doc', 'GREENHOUSE', 'doc', 'https://boards.greenhouse.io/doc'),
('Vmax', 'GREENHOUSE', 'vmax', 'https://boards.greenhouse.io/vmax'),
('Pronto', 'GREENHOUSE', 'pronto', 'https://boards.greenhouse.io/pronto'),
('Community', 'GREENHOUSE', 'community', 'https://boards.greenhouse.io/community'),
('Cleo', 'GREENHOUSE', 'cleo', 'https://boards.greenhouse.io/cleo'),
('Trolley', 'GREENHOUSE', 'trolley', 'https://boards.greenhouse.io/trolley'),
('Route', 'GREENHOUSE', 'route', 'https://boards.greenhouse.io/route'),
('Tamara', 'GREENHOUSE', 'tamara', 'https://boards.greenhouse.io/tamara'),
('Pcm', 'GREENHOUSE', 'pcm', 'https://boards.greenhouse.io/pcm'),
('Radar', 'GREENHOUSE', 'radar', 'https://boards.greenhouse.io/radar'),
('Crescent', 'GREENHOUSE', 'crescent', 'https://boards.greenhouse.io/crescent'),
('Impact', 'GREENHOUSE', 'impact', 'https://boards.greenhouse.io/impact'),
('Remedy', 'GREENHOUSE', 'remedy', 'https://boards.greenhouse.io/remedy'),
('Action', 'GREENHOUSE', 'action', 'https://boards.greenhouse.io/action'),
('Axle', 'GREENHOUSE', 'axle', 'https://boards.greenhouse.io/axle'),
('Eve', 'GREENHOUSE', 'eve', 'https://boards.greenhouse.io/eve'),
('Wasabi', 'GREENHOUSE', 'wasabi', 'https://boards.greenhouse.io/wasabi'),
('Zam', 'GREENHOUSE', 'zam', 'https://boards.greenhouse.io/zam'),
('Rehabilitation', 'GREENHOUSE', 'rehabilitation', 'https://boards.greenhouse.io/rehabilitation'),
('Goodwin', 'GREENHOUSE', 'goodwin', 'https://boards.greenhouse.io/goodwin'),
('Trident', 'GREENHOUSE', 'trident', 'https://boards.greenhouse.io/trident'),
('Bird', 'GREENHOUSE', 'bird', 'https://boards.greenhouse.io/bird'),
('Honor', 'GREENHOUSE', 'honor', 'https://boards.greenhouse.io/honor'),
('Inter', 'GREENHOUSE', 'inter', 'https://boards.greenhouse.io/inter'),
('Block', 'GREENHOUSE', 'block', 'https://boards.greenhouse.io/block'),
('Cherry', 'GREENHOUSE', 'cherry', 'https://boards.greenhouse.io/cherry'),
('Fruitful', 'GREENHOUSE', 'fruitful', 'https://boards.greenhouse.io/fruitful'),
('Pulse', 'GREENHOUSE', 'pulse', 'https://boards.greenhouse.io/pulse'),
('Cio', 'GREENHOUSE', 'cio', 'https://boards.greenhouse.io/cio'),
('Edo', 'GREENHOUSE', 'edo', 'https://boards.greenhouse.io/edo'),
('Mercury', 'GREENHOUSE', 'mercury', 'https://boards.greenhouse.io/mercury'),
('Bravo', 'GREENHOUSE', 'bravo', 'https://boards.greenhouse.io/bravo'),
('Jumia', 'GREENHOUSE', 'jumia', 'https://boards.greenhouse.io/jumia'),
('Noble', 'GREENHOUSE', 'noble', 'https://boards.greenhouse.io/noble'),
('Retail', 'GREENHOUSE', 'retail', 'https://boards.greenhouse.io/retail'),
('Ever', 'GREENHOUSE', 'ever', 'https://boards.greenhouse.io/ever'),
('Nice', 'GREENHOUSE', 'nice', 'https://boards.greenhouse.io/nice'),
('Markets', 'GREENHOUSE', 'markets', 'https://boards.greenhouse.io/markets'),
('Emerge', 'GREENHOUSE', 'emerge', 'https://boards.greenhouse.io/emerge'),
('Tca', 'GREENHOUSE', 'tca', 'https://boards.greenhouse.io/tca'),
('Quince', 'GREENHOUSE', 'quince', 'https://boards.greenhouse.io/quince'),
('Des', 'GREENHOUSE', 'des', 'https://boards.greenhouse.io/des'),
('Golf', 'GREENHOUSE', 'golf', 'https://boards.greenhouse.io/golf'),
('Genesis', 'GREENHOUSE', 'genesis', 'https://boards.greenhouse.io/genesis'),
('Technical', 'GREENHOUSE', 'technical', 'https://boards.greenhouse.io/technical'),
('Onyx', 'GREENHOUSE', 'onyx', 'https://boards.greenhouse.io/onyx'),
('Squad', 'GREENHOUSE', 'squad', 'https://boards.greenhouse.io/squad'),
('Purple', 'GREENHOUSE', 'purple', 'https://boards.greenhouse.io/purple'),
('Scotch', 'GREENHOUSE', 'scotch', 'https://boards.greenhouse.io/scotch'),
('Shein', 'GREENHOUSE', 'shein', 'https://boards.greenhouse.io/shein'),
('Essential', 'GREENHOUSE', 'essential', 'https://boards.greenhouse.io/essential'),
('Lincoln', 'GREENHOUSE', 'lincoln', 'https://boards.greenhouse.io/lincoln'),
('Escada', 'GREENHOUSE', 'escada', 'https://boards.greenhouse.io/escada'),
('India', 'GREENHOUSE', 'india', 'https://boards.greenhouse.io/india'),
('Oasis', 'GREENHOUSE', 'oasis', 'https://boards.greenhouse.io/oasis'),
('Escala', 'GREENHOUSE', 'escala', 'https://boards.greenhouse.io/escala'),
('Vts', 'GREENHOUSE', 'vts', 'https://boards.greenhouse.io/vts'),
('Petcare', 'GREENHOUSE', 'petcare', 'https://boards.greenhouse.io/petcare'),
('Vega', 'GREENHOUSE', 'vega', 'https://boards.greenhouse.io/vega'),
('Claros', 'GREENHOUSE', 'claros', 'https://boards.greenhouse.io/claros'),
('Remote', 'GREENHOUSE', 'remote', 'https://boards.greenhouse.io/remote'),
('Byd', 'GREENHOUSE', 'byd', 'https://boards.greenhouse.io/byd'),
('Firstchoice', 'GREENHOUSE', 'firstchoice', 'https://boards.greenhouse.io/firstchoice'),
('Camp', 'GREENHOUSE', 'camp', 'https://boards.greenhouse.io/camp'),
('Greenhouse', 'GREENHOUSE', 'greenhouse', 'https://boards.greenhouse.io/greenhouse');
ON CONFLICT (board_token) DO UPDATE 
SET name = EXCLUDED.name, ats_type = EXCLUDED.ats_type;