server:
  port: 8082

spring:
  application:
    name: analytics-engine

  # Non-blocking R2DBC Database Connection
  r2dbc:
    r2dbc:
    url: r2dbc:postgresql://${DB_HOST:127.0.0.1}:5432/analytics_db
    username: postgres # (or respective db n
    password: ${POSTGRES_PASSWORD:password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 70
      max-acquire-time: 10s
      initialization-fail-fast: true

  # Reactive Redis Connection
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379