server:
  port: 8084

spring:
  application:
    name: job-validator
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

scraper:
  target: greenhouse  # Options: greenhouse, lever, workable, talentera

logging:
  level:
    # Your custom logs
    com.distributed.job_validator: INFO
    # Suppress WebClient internal logs
    org.springframework.web.reactive.function.client.WebClient: WARN
    # Suppress Netty SSL/TLS Handshake Timeout stack traces
    reactor.netty.http.client.HttpClientConnect: ERROR
    reactor.netty.http.client.HttpClient: ERROR