server:
  port: 8084

spring:
  application:
    name: job-validator
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# 👇 Add this block to control which runner executes
scraper:
  target: workable  # Options: workable, talentera, or none

logging:
  level:
    # Shows your custom log messages (like ✅ SUCCESS or ❌ Miss)
    com.distributed.job_validator: INFO
    # Suppresses the massive amount of internal WebClient network logs
    org.springframework.web.reactive.function.client.WebClient: WARN