server:
  port: 8083 # Runs on a dedicated port so your API Gateway (8080) can route traffic to it

spring:
  application:
    name: job-finder
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  # 1. PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/job_finder_db 
    username: postgres
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 # Prevents the scraper from opening too many DB connections at once

  # 2. JPA & Hibernate Settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate 
    show-sql: true     # Prints the executed SQL queries to your terminal
    properties:
      hibernate:
        format_sql: true # Formats the printed SQL so it is actually readable

  # 3. Redis Configuration (For your Ingestion Stream)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000

# 4. Custom Application Properties
app:
  scraper:
    talentera:
      target-boards:
        - aab
        - tra
        - royaljordanian
        - mobica
        - masar
        - tamimi
        - mobily
        - orangebedbath
        - magrabi
        - rawabi
        - itqan
        - chi
        - radwa
        - careers
        - integral
        - ncec
        - panda
        - beam
        - care
        - badruddin
        - saib
        - gosi
        - al-dawaa
        - savethechildren
        - taiba
        - concrete
        - maliks
        - ejada
        - demo
        - sba
        - choithrams
        - alfardan
        - gib
        - msd
        - sal
        - spsp
        - batelco
        - nwc
        - cma
        - modon
        - alrashed
    webclient:
      timeout-ms: 5000 # If an ATS API goes down, WebClient gives up after 5 seconds instead of hanging
    workable:
      target-boards:
        - visioneers # You can add more separated by commas later if your code splits them
    greenhouse:
      base-url: "https://boards-api.greenhouse.io/v1/boards"
      target-boards:
        - gps
        - london
        - orca
        - spotlight
        - kayak
        - national
        - alx
        - gemini
        - concentric
        - magnolia
        - stage
        - galileo
        - raven
        - super
        - digit
        - apollo
        - tulip
        - pvi
        - denver
        - chicago
        - tide
        - flourish
        - bob
        - brothers
        - taa
        - regent
        - nex
        - abc
        - flamingo
        - glow
        - reflex
        - korea
        - its
        - coast
        - indigo
        - metropolis
        - oldcity
        - paradigm
        - alabaster
        - octave
        - reliant
        - headquarter
        - lightworks
        - bloom
        - rak
        - shield
        - upkeep
        - truemedia
        - soci
        - dna
        - administrative
        - athletics
        - sei
        - metro
        - athena
        - support
        - hunterdouglas
        - zoro
        - carbon
        - greenline
        - pioneer
        - yes
        - avani
        - help
        - eclipse
        - jaguar
        - dino
        - koko
        - rmr
        - new
        - sao
        - tomorrow
        - stone
        - seed
        - iris
        - comet
        - investment
        - ghost
        - casa
        - nursing
        - shaker
        - encore
        - range
        - ref
        - moneymart
        - excel
        - optimal
        - gateway
        - reach
        - slice
        - forward
        - fox
        - isa
        - murad
        - sunrise
        - sada
        - pine
        - charles
        - proton
        - clever
        - sts
        - private
        - netherlands
        - hala
        - amca
        - truckstop
        - moon
        - boulevard
        - parkland
        - axiom
        - newhope
        - sonic
        - techno
        - genuine
        - careem
        - tribal
        - drc
        - homeland
        - vibes
        - mesh
        - chata
        - cabin
        - kansas
        - polaris
        - peak
        - magic
        - oscar
        - mobi
        - broadway
        - efs
        - sterling
        - integrated
        - isam
        - link
        - evergreen
        - ideo
        - candles
        - flex
        - gusto
        - maxwell
        - make
        - industrial
        - mit
        - wundermanthompson
        - talent
        - independent
        - makina
        - david
        - tcs
        - firstday
        - calm
        - sas
        - victory
        - emi
        - nexus
        - regie
        - solutions
        - b12
        - dallas
        - sabino
        - kit
        - japan
        - antigua
        - imc
        - testing
        - elitetechnology
        - general
        - gravity
        - tss
        - sunset
        - jay
        - scanner
        - workshop
        - explore
        - flix
        - space
        - universal
        - journey
        - tec
        - galaxy
        - branch
        - echo
        - location
        - shadow
        - edison
        - tiptop
        - philippines
        - name
        - mas
        - res
        - tpm
        - lighthouse
        - champion
        - ensemble
        - bold
        - bridgeway
        - clear
        - any
        - newton
        - cts
        - joya
        - finance
        - axon
        - aziz
        - symphony
        - aura
        - coop
        - gmp
        - future
        - locals
        - orchestra
        - cycles
        - contracts
        - bees
        - shepherd
        - daylight
        - hologram
        - pharmacy
        - ultimate
        - vaya
        - engine
        - intercom
        - events
        - find
        - test
        - keen
        - public
        - highland
        - sra
        - forte
        - disney
        - lor
        - flash
        - berelaxspa
        - air
        - cannondale
        - silicon
        - fourstar
        - prisma
        - international
        - beyond
        - cais
        - colorado
        - spain
        - zoo
        - genius
        - aha
        - village
        - nectar
        - lush
        - supreme
        - transform
        - alliance
        - festival
        - apex
        - kite
        - rga
        - icon
        - rab
        - esri
        - basic
        - place
        - allied
        - blend
        - selling
        - osmosis
        - goal
        - map
        - summer
        - alta
        - maro
        - fourseasons
        - elite
        - ampm
        - maestro
        - via
        - ohio
        - a24
        - alu
        - technology
        - glance
        - tekla
        - neu
        - system
        - insurance
        - education
        - harbor
        - moltonbrown
        - uplift
        - pia
        - network
        - grey
        - lasenza
        - doc
        - vmax
        - pronto
        - community
        - cleo
        - trolley
        - route
        - tamara
        - pcm
        - radar
        - crescent
        - impact
        - remedy
        - action
        - axle
        - eve
        - wasabi
        - zam
        - rehabilitation
        - goodwin
        - trident
        - bird
        - honor
        - inter
        - block
        - cherry
        - fruitful
        - pulse
        - cio
        - edo
        - mercury
        - bravo
        - jumia
        - noble
        - retail
        - ever
        - nice
        - markets
        - emerge
        - tca
        - quince
        - des
        - golf
        - genesis
        - technical
        - onyx
        - squad
        - purple
        - scotch
        - shein
        - essential
        - lincoln
        - escada
        - india
        - oasis
        - escala
        - vts
        - petcare
        - vega
        - claros
        - remote
        - byd
        - firstchoice
        - camp
        - greenhouse
    lever:
      base-url: "https://api.lever.co/v0/postings"

# 5. Logging Configuration
logging:
  level:
    root: INFO
    # Set to DEBUG to watch exactly what HTTP requests WebClient is firing
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG 
    org.hibernate.SQL: DEBUG